### ISSUE TITLE
How to bundle several smart contract invocations into a single tx?

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neo-python#100]
I would love to be able to bundle several smart contract invocations into a single transaction.

If anyone wants to take a stab at this, that would be great! If not, perhaps at some later date I'll find enough time to try taking a look. I think this feature will become an increasingly important thing to do for more complex SC interactions.

Adding this ticket mainly to keep track of any development and references.

**Comment by snowypowers** [comment]
I am successful in chaining vm scripts together. At least for minor stuff like retrieving names, symbol, etc. It works in `invokescript` RPC call so I don't see why not with a real transaction.

You can take a look at https://github.com/CityOfZion/neon-js/blob/081bc4c42422f1eb9f51bf955e93ac28111888c1/src/nep5.js#L14 . Each `emitAppCall` is basically one invocation.

**Comment by localhuman** [comment]
Resolved in https://github.com/CityOfZion/neo-python/pull/137
