### ISSUE TITLE
tkn_send creates invalid tx, testinvoke creates valid tx but funds are not processed

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo-python#101]
```
wallet tkn_send RPX <wallet address> <destination address> 1
```
I get a prompt asking to confirm + password. Then I see
```
Verifying transaction: <txid>
Relayed TX: <txid>
```
But when then trying to run:
```
tx <txid> 
```
I get the response
```
Could not find transaction for hash <txid>
```
even after 30+ blocks have been processed.

Alternatively, doing the following as suggested by @localhuman 
```
testinvoke {hash} 0710 05 True transfer ['from_addr', 'to_addr', 1]
```
where
`hash` is the token `script_hash` (under the Token[idx].script_hash key of the Wallet)
`from_addr` is public_keys[idx].Address key of the wallet holding the tokens
`to_addr` is the destination address (LEN:34)

This does instantly create a valid `txid` that can be queried using `tx <txid>`. However the funds are never deducted.

Development branch: db617bf37e7ea303c9fa2fabd81584cf418f1756
MainNet

**Comment by localhuman** [comment]
The following all work for me:
- `wallet tkn_send NEP5 AXjaFSP23Jkbe6Pk9pPGT6NBDs1HVdqaXK AdMDZGto3xWozB1HSjjVv27RL3zUM8LzpV 60000` results in `c878257216d549d3afbae6984f949f9f5f4af9b1d97577e7179fa00cf832e9c5`
 
- `testinvoke f8d448b227991cf07cb96a6f9c0322437f1599b9 transfer ['AXjaFSP23Jkbe6Pk9pPGT6NBDs1HVdqaXK','AdMDZGto3xWozB1HSjjVv27RL3zUM8LzpV',12345]` results in `659a1de5d7d163454482887ffb0f8086d55f4d407df49b7c431ecd302125e5a6 `

- This syntax will also work: `send NEP5 AdMDZGto3xWozB1HSjjVv27RL3zUM8LzpV 5000 --from-addr=AXjaFSP23Jkbe6Pk9pPGT6NBDs1HVdqaXK` results in `9f8f1abdc899c8bcca6ab00cbd917e6c314cd1745fa9b7884993e38aebd8b6d2`

**Comment by ixje** [comment]
So I closed the wallet, re-opened it; ran the exact same command as before (using the cli history)
`wallet tkn_send RPX <wallet address> <destination address> 1` 
this time it did create a valid `txid` _and_ the funds are deducted.

Maybe re-opening after having fully synced initialises the wallet different, I don't know. 

What do you want to do with the issue as it magically resolved itself? Keep it open for future investigatio or close it?

**Comment by metachris** [comment]
If there is a way to reproduce them, I would keep it or make a new ticket for it. If it is not reproducible I suggest to close the ticket.
