### ISSUE TITLE
BigInteger ToByteArray incompatible with neo-vm v3.0.0

### ISSUE THREAD

**Issue by LiveOverflow** [CityOfZion/neo-python#1025]
Recently the behavior of the ToByteArray conversion from the BigInteger(0) was changed in neo-vm for version 3.x to return an empty array: https://github.com/neo-project/neo-vm/pull/173

`neo-python` hasn't implemented this change yet and still returns the bytearray `'\x00`.

**Comment by ixje** [comment]
Hi, 
Thank you for the report. I first have to point out that this repository will stay Neo `2.x` only and a separate `3.x` repository will be created such that we can have a clear separation for issues and roadmaps. We're working on the background on a mostly re-written version for `3.x` which focuses on being an SDK first. Once the core features are implemented we'll make it public. I've updated this repository title to reflect this.

Having said the above I hope you'll understand that I'm closing this issue for this repository.
