### ISSUE TITLE
Interesting events to broadcast

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neo-python#103]
I've been thinking of interesting events that neo-python could broadcast via the EventHub. Interesting for instance for third party developers, or the prompt.py ui.

For instance:

* Node connected / disconnected
* Block received, Block height updated

Also possible:

* Balance changes of addresses

Issue for brainstorming, please leave comments with further thoughts and ideas.

**Comment by localhuman** [comment]
Another one:
- Wallet synced

**Comment by ixje** [comment]
Closing due to focus on NEO3
