### ISSUE TITLE
运行np-prompt后，prompt.log中报错，

### ISSUE THREAD

**Issue by helailiang** [CityOfZion/neo-python#1035]
$ np-prompt
[I 200430 15:58:00 Settings:359] Created 'Chains' directory at /home/neo/.neopython/Chains 
Maxpeers set to  5
[I 200430 15:58:01 LevelDBImpl:45] Created DB at /home/neo/.neopython/Chains/SC234 
[I 200430 15:58:01 LevelDBImpl:45] Created DB at /home/neo/.neopython/Chains/Test_Notif 

==================prompt.log======================
$ vi prompt.log 
[I 200430 15:58:01 LevelDBImpl:45] Created DB at /home/neo/.neopython/Chains/SC234
[D 200430 15:58:01 Block:252] Rebuilding merkle root!
[D 200430 15:58:01 Block:252] Rebuilding merkle root!
[D 200430 15:58:01 Blockchain:628] Could not get sys fee: 'NoneType' object is not subscriptable
[I 200430 15:58:01 LevelDBImpl:45] Created DB at /home/neo/.neopython/Chains/Test_Notif
~

**Comment by ixje** [comment]
use the issue reporting template
