### ISSUE TITLE
Sudden high memory usage running prompt.py

### ISSUE THREAD

**Issue by MediaServe** [CityOfZion/neo-python#117]
I'm running a Python node on my workstation on NEO TestNet for almost three weeks now. Suddenly my workstation starts running slow. The Python process was using a lot of resources (over 12 GB memory and about 50% CPU) and the usage was climbing quite quickly. I had to shutdown the node.

Command:
> python prompt.py -t

Last state of the node:
> [TestNet] Progress: 884333/884402

Environment:
> Ubuntu 16.04 LTS
> Python 3.5.2

Version:
> Commit: fe5f65ff2c45fc1deddb06646e926a03df363a0b

I'm having no further issues with my workstation.

[last_console.log](https://github.com/CityOfZion/neo-python/files/1559489/last_console.log)

**Comment by localhuman** [comment]
Could you pull down the latest and see if you can replicate on `v0.4.1`?

**Comment by localhuman** [comment]
I'm going to close this issue.  If you see it occur again feel free to open a new issue.
