### ISSUE TITLE
Invoking a (Java) smart contract that is using Runtime.log("..") will cause: "COULD NOT GET STR LENGTH!" could not execute command: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by popsteegh** [CityOfZion/neo-python#121]
Invoking a (Java) smart contract that is using Runtime.log("..") in the Main method will cause the following error: 

COULD NOT GET STR LENGTH! could not execute command: maximum recursion depth exceeded
...
File "/neo-python/neo/VM/InteropService.py", line 349, in stack_item_to_py
    return [stack_item_to_py(item) for item in stack_item.GetArray()]
RecursionError: maximum recursion depth exceeded

**Comment by metachris** [comment]
Interesting. Can you post the SC, or a reduced version that allows to reproduce this behaviour?

**Comment by popsteegh** [comment]
This happens when you add a trace log statement using Runtime.log(..) that concatenates a String, for instance:

public static boolean Main(boolean b) {
    Runtime.log("Main("
        + "b=" +             
        + ")");
        return true;
    }
}

Without the concatenation it works just fine. For instance, doing:

    Runtime.log("Main()"); 

does not cause this problem.

**Comment by localhuman** [comment]
Does this run in the C# VM?

**Comment by popsteegh** [comment]
I'm running a smart contract written in Java on the neo-privatenet-docker using the NEO python node / SDK.

**Comment by localhuman** [comment]
Hi @popsteegh 

I'm not familiar with the Java compiler, but I have a feeling this wouldn't work in the C# VM. 
 If you could attach the compiled .avm file I could test it out.

Usually ( at least with a SC compiled with python ) strings need to use the special `concat` method to be concatenated.

**Comment by popsteegh** [comment]
Hi @localhuman,

Sorry for the delay, busy (Christmas) times ;)

Please find attached the .avm file that you can test out (I had to zip it, because GitHub does not support attaching .avm files)

[Test.avm.zip](https://github.com/CityOfZion/neo-python/files/1585877/Test.avm.zip)

**Comment by fannix** [comment]
I tested on C# VM, and can confirm that string concatenation didn't work.
