### ISSUE TITLE
rror No module named 'logzero'

### ISSUE THREAD

**Issue by plash29** [CityOfZion/neo-python#133]
When i run **python bootstrap.py** it give this **error No module named 'logzero'.**

Traceback (most recent call last):
  File "bootstrap.py", line 1, in <module>
    from neo.Settings import settings
  File "D:\python\neo-python-master\neo\Settings.py", line 14, in <module>
    import logzero
ImportError: No module named 'logzero'

**Comment by metachris** [comment]
Did you setup the virtualenv and installed the dependencies as described in the readme? Is yes, please post the output of `python -V` and `pip -v` and `pip freeze`.

**Comment by plash29** [comment]
$ python -V
Python 3.5.4
---------------------------------------------------------
$ pip -v

Usage:
  pip <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  list                        List installed packages.
  show                        Show information about installed packages.
  check                       Verify installed packages have compatible dependencies.
  search                      Search PyPI for packages.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes of package archives.
  completion                  A helper command used for command completion.
  help                        Show help for commands.

General Options:
  -h, --help                  Show help.
  --isolated                  Run pip in an isolated mode, ignoring
                              environment variables and user configuration.
  -v, --verbose               Give more output. Option is additive, and can be
                              used up to 3 times.
  -V, --version               Show version and exit.
  -q, --quiet                 Give less output. Option is additive, and can be
                              used up to 3 times (corresponding to WARNING,
                              ERROR, and CRITICAL logging levels).
  --log <path>                Path to a verbose appending log.
  --proxy <proxy>             Specify a proxy in the form
                              [user:passwd@]proxy.server:port.
  --retries <retries>         Maximum number of retries each connection should
                              attempt (default 5 times).
  --timeout <sec>             Set the socket timeout (default 15 seconds).
  --exists-action <action>    Default action when a path already exists:
                              (s)witch, (i)gnore, (w)ipe, (b)ackup, (a)bort.
  --trusted-host <hostname>   Mark this host as trusted, even though it does
                              not have valid or any HTTPS.
  --cert <path>               Path to alternate CA bundle.
  --client-cert <path>        Path to SSL client certificate, a single file
                              containing the private key and the certificate
                              in PEM format.
  --cache-dir <dir>           Store the cache data in <dir>.
  --no-cache-dir              Disable the cache.
  --disable-pip-version-check
                              Don't periodically check PyPI to determine
                              whether a new version of pip is available for
                              download. Implied with --no-index.
----------------------------------------------------------------------------
$ pip freeze
asn1crypto==0.23.0
attrs==17.3.0
Automat==0.6.0
autopep8==1.3.3
base58==0.2.5
bitcoin==1.1.42
blessings==1.6
bpython==0.16
byteplay3==3.5.0
certifi==2017.11.5
cffi==1.11.2
chardet==3.0.4
colorama==0.3.9
colorlog==3.1.0
constantly==15.1.0
coverage==4.4.2
coveralls==1.2.0
cryptography==2.1.3
curtsies==0.2.11
cycler==0.10.0
docopt==0.6.2
ecdsa==0.13
Events==0.3
gevent==1.2.2
greenlet==0.4.12
hyperlink==17.3.1
idna==2.6
incremental==17.5.0
pycodestyle==2.3.1
pycparser==2.18
Pygments==2.2.0
requests==2.18.4
six==1.11.0
urllib3==1.22
virtualenv==15.1.0
virtualenvwrapper-win==1.2.5
wcwidth==0.1.7
Werkzeug==0.13
zope.interface==4.4.3

**Comment by metachris** [comment]
It seems that you didn't install the dependencies. Follow the readme to setup the virtualenv and install the dependencies.
