### ISSUE TITLE
Improving error handling with neocore

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neo-python#152]
It would be great if we would improve the error handling at some point. I'd like to remove the logzero dependency from [`neocore`](https://github.com/CityOfZion/neo-python-core) and throw exceptions instead of logging errors and returning default values. This will need some refactoring on the implementation points in neo-python. 

Not a hurry, but I think would improve the overall robustness and usability of neocore.

**Comment by ixje** [comment]
done
