### ISSUE TITLE
[Feature] Integrate transfer notifications for NEP5 into wallet

### ISSUE THREAD

**Issue by localhuman** [CityOfZion/neo-python#162]
With transfer notifications now persisting #155 we are able to show a balance history for NEP5 tokens in the wallet.  This feature request proposes integrating those transfer notifications into `UserWallet` so that users can see their NEP5 token transfer history.

**Comment by daghdha** [comment]
hi there, so what we are thinking about is looking up in the notificationDB for those transfer notifications and displaying them through the UserWallet? just want to check to see as I was going to try to take a stab at it. :)

**Comment by localhuman** [comment]
That is correct, let us know with any questions!

**Comment by daghdha** [comment]
ok, (sorry, this is my first time contributing to this, so just figure I would ask...) if I'm getting this right, am I going to be implementing in prompt.py the wallet tkn-history with the token symbol, then use prompt.py to search through the notificationDB for the appropriate transfers for this particular wallet and display to the user?  You mentioning UserWallet makes me think I'm barking up the wrong tree and it would be more "inline" with the architecture here to instantiate a notificationDB in UserWallet and then do the logic all in there.  Don't know what is the typical way of doing things here in neo-python, so figure i would ask.  then again, there is a hackit label. :)

**Comment by localhuman** [comment]
I believe @dethos has implemented this :)
