### ISSUE TITLE
Generating a Send Transaction Without Syncing Balance

### ISSUE THREAD

**Issue by lionelyoung** [CityOfZion/neo-python#165]
Is there a way to generate the Send Transaction without syncing the balance?

When create a UserWallet using UserWallet.Open(), it won't send any transactions due to "insufficient balance"

**Comment by localhuman** [comment]
`neo-python` does not function as a light wallet, so you will need to sync your wallet before using it to send system assets such as NEO or Gas.

If you'd like to speed up the sync of your wallet, after creating a wallet you can do `wallet rebuild {current block number} and it will start out fully synced.
