### ISSUE TITLE
docker_build.sh - if neo-cli.zip can not be downloaded empty zip files are created and build fails

### ISSUE THREAD

**Issue by overqint** [CityOfZion/neo-python#168]
For example if wget in docker_build.sh can not download the 
https://github.com/neo-project/neo-cli/releases/download/v2.5.2/neo-cli-ubuntu.16.04-x64.zip

2 files with 0 size are generated:
-rw-r--r--   1 user  staff     0B 15 Jan 09:29 neo-cli.zip
-rw-r--r--   1 user  staff     0B 15 Jan 09:29 neo-release-2.5.2.zip

This again causes the build fail:

> Step 13/40 : RUN unzip -q -d /opt/node1 /opt/neo-cli.zip
>  ---> Running in 3ed4eb892609
> [/opt/neo-cli.zip]
>   End-of-central-directory signature not found.  Either this file is not
>   a zipfile, or it constitutes one disk of a multi-part archive.  In the
>   latter case the central directory and zipfile comment will be found on
>   the last disk(s) of this archive.
> #!/bin/bash
> unzip:  cannot find zipfile directory in one of /opt/neo-cli.zip or
>         /opt/neo-cli.zip.zip, and cannot find /opt/neo-cli.zip.ZIP, period.

Solved this problem with using the 
--no-check-certificate for wget in my case.
`wget --no-check-certificate -O https://github.com/neo-project/neo-cli/releases/download/v2.5.2/neo-cli-ubuntu.16.04-x64.zip`

But the underlying problem should be solved in my opinion:
If files are not downloaded in a correct manner:
`docker build -t neo-privnet .`
should not be executed

**Comment by metachris** [comment]
I think this PR is for https://github.com/CityOfZion/neo-privatenet-docker?

**Comment by metachris** [comment]
Should be fixed with https://github.com/CityOfZion/neo-privatenet-docker/pull/24
