### ISSUE TITLE
[Feature] Implement new voting changes

### ISSUE THREAD

**Issue by localhuman** [CityOfZion/neo-python#169]
Recent changes in NEO core added a new Transaction type along with a number of other large changes around voting and consensus.  These changes should be implemented in `neo-python`.

New changes in NEO:
https://github.com/neo-project/neo/pull/130

**Comment by localhuman** [comment]
I've pushed a new branch for these changes here: https://github.com/CityOfZion/neo-python/tree/feature-state-transaction

These are the non-consensus related changes we will be needing for sure:
- add `neo.Core.StateDescriptor`
- add `neo.Core.TX.StateTransaction`
- update `neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.PersistBlocks` to handle the new `StateTransaction`

There are probably additional changes needed as well, but these will provide a start.

**Comment by ixje** [comment]
reminder for #67
