### ISSUE TITLE
Add data type conversion questions to documentation

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neo-python#183]
Example:

* Q: "Whats the best way to convert a script hash to a python byte array, eg `b'#\xba\'\x03\xc52c\xe8\xd6\xe5"\xdc2 39\xdc\xd8\xee\xe9'`"
* A: if you have `UInt160`, its just `scripthash.Data`

**Comment by localhuman** [comment]
Should be addressed in this https://github.com/CityOfZion/neo-python/pull/285
