### ISSUE TITLE
JSON RPC API Functionality

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neo-python#189]
Work in progress, now already in dev. See also https://github.com/CityOfZion/neo-python/issues/273 for tracking issues.

Links:

* http://docs.neo.org/en-us/node/api.html
* https://github.com/neo-project/neo/blob/master/neo/Network/RPC/RpcServer.cs
* http://www.jsonrpc.org/specification
* [dry coded rpc server bodies by @ixje](https://gist.github.com/ixje/eb8e6fef5011d0232e6b44b7097da584)
* [example calls at neo-cli-json-rpc-docs.md](https://github.com/CityOfZion/neo-python/blob/jsonrpc1/neo/api/JSONRPC/neo-cli-json-rpc-docs.md)

Initial calls:

- [X] getaccountstate
- [X] getbestblockhash
- [X] getblockcount
- [X] getblockhash
- [X] getblocksysfee
- [X] getconnectioncount
- [X] getrawmempool
- [x] getpeers
- [X] getrawtransaction
- [X] getstorage
- [X] getversion
- [X] sendrawtransaction
- [X] validateaddress
- [X] invoke
- [X] invokefunction
- [X] invokescript
- [X] getassetstate
- [X] getblock (int)
- [X] getblock (hash)
- [X] gettxout (the C# side is broken [#156](https://github.com/neo-project/neo/issues/156))
- [X] getcontractstate (TODO: can't successfully run this call against the live nodes)
- [x] getbalance
- [x] getnewaddress

Additional calls

- [x] listaddress ([more info](https://github.com/neo-project/neo-cli/issues/87#event-1443067788))
- [ ] getapplicationlog ([more info](https://github.com/neo-project/neo-cli/pull/102/files))
- [ ] dumpprivkey
- [x] sendtoaddress
- [x] sendmany

See also:

* https://github.com/CityOfZion/neo-python/issues/233 (JsonRpcApi input & output differs from C#)

**Comment by ixje** [comment]
fyi; I'm working on `gettxout`, but the C# side is broken [#156](https://github.com/neo-project/neo/issues/156)

**Comment by metachris** [comment]
added 2 new calls to the list: 

* listaddress ([see this](https://github.com/neo-project/neo-cli/issues/87#event-1443067788))
* getapplicationlog ([see this](https://github.com/neo-project/neo-cli/pull/102/files))

**Comment by ixje** [comment]
The list can be updated as follows:

**initial calls**
* check `getstorage`

**Implemented, but giving different results from neo-cli**
* `getassetstate` and `getblock` are done and can be moved to the top list and checked.

**Problems**
* `gettxout` can be moved to initial and checked
*  `getcontractstate` is implemented, but I can't validate it against the C# node as their examples are not working. I tried running the `RPX` contract hash (that we use in our tests) against the C# RPC call but it still throws "Unknown contract". Should investigate more

**Additional calls**
the following can be checked as implemented
`invoke`
`invokescript`
`invokefunction`
`validateaddress`

**Comment by metachris** [comment]
Updated the list. Should we keep this issue open as a reminder what we could do?

**Comment by dethos** [comment]
@metachris I think we can update the issue checklist. `getpeers` and `listaddress` were implemented since the last update.

**Comment by metachris** [comment]
Thanks, done

**Comment by dethos** [comment]
@metachris perhaps we could update the checklist again. From the unchecked items, `sendtoaddress` and `sendmany` were already added.

**Comment by dethos** [comment]
`getapplicationlog` seems to no longer exist on [version `2.9.0` of `neo-cli` documentation](http://docs.neo.org/en-us/node/cli/2.9.0/api.html). Perhaps it should be removed from the list, no?

**Comment by ixje** [comment]
deviations from the NEO JSON api are generally reported in separate issues by users. I don't think this post has any use anymore.
