### ISSUE TITLE
Neo Blockchain Python Smart Contract compiler

### ISSUE THREAD

**Issue by JGdBB** [CityOfZion/neo-python#215]
Hi,

I have followed your tutorial on youtube : https://www.youtube.com/watch?v=oy6Z_zd42-4
The contract is at 1:22 and the command at 6:09
I have followed all the instructions but my whole neo-python hangs

neo> build ./contracts/WhileTest.py test '' 02 False False
Saved output to ./contracts/WhileTest.avm
creating instance!
created begustorage
cloining from live!
cloned db
self contract properties: 3

Thanks you very much for your help !

**Comment by metachris** [comment]
i think it should be `build ./contracts/WhileTest.py test 05 02 False False`

**Comment by ixje** [comment]
the `WhileTest.py` doesn't have any arguments for Main. I discussed this item yesterday on Discord and even tried using the `void` (0xFF) parameter and that also doesn't work. As you'll see in the video Tom also uses the commands above (with '' for no arguments). I do think this is a bug somewhere as my whole `neo-python` hangs with this test case. The video is quite old so there might have been some changes that breaks this.

**Comment by localhuman** [comment]
I believe there at some point was a change to the compiler and it no longer works with the break statement in the while loop, so it is an unterminated loop.  We should perhaps remove that example for now in the compiler, or fix the issue with it.
