### ISSUE TITLE
Using neo-python as a library

### ISSUE THREAD

**Issue by thdxr** [CityOfZion/neo-python#219]
I attempted to install `neo` from pip to use it as a library.  However it seems to only pull in the files in the `neo` folder and none of its subfolders.  I'm new to Python so I'm not sure if this is intentional or not.  Am I supposed to fork this entire codebase if I want to run custom code like it shows in the examples?

Contents of my `site-packages/neo`
```
total 56K
drwxr-xr-x   3 dax 4.0K Feb 13 15:55 .
drwxr-xr-x 127 dax  12K Feb 13 15:55 ..
drwxr-xr-x   2 dax 4.0K Feb 13 15:55 __pycache__
-rw-r--r--   1 dax 2.5K Jan 24 08:16 BigInteger.py
-rw-r--r--   1 dax  665 Jan 24 08:16 Blockchain.py
-rw-r--r--   1 dax 3.7K Jan 24 08:16 EventHub.py
-rw-r--r--   1 dax   22 Jan 24 08:16 __init__.py
-rw-r--r--   1 dax 5.5K Jan 24 08:16 Settings.py
-rw-r--r--   1 dax 2.0K Jan 24 08:16 test_preferences.py
-rw-r--r--   1 dax 1.2K Jan 24 08:16 test_settings.py
-rw-r--r--   1 dax 2.3K Jan 24 08:16 UserPreferences.py
```

**Comment by metachris** [comment]
Yeah, for now you need to simply clone the repository, and setup the venv as described in the README.

**Comment by thdxr** [comment]
Is there a plan to be able to use it as a library?

**Comment by metachris** [comment]
yes, it's on the radar, and will come at some point. it's not a priority though.
