### ISSUE TITLE
ContractParameterType.py#64 in ToName: TypeError: int() argument must be a string, a bytes-like object or a number, not 'ContractParameterType'

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neo-python#240]
In https://github.com/CityOfZion/neo-privatenet-docker we have a new issue with neo-python (both master and dev branches). The send_neo method here calls `context.ToJson()`: https://github.com/CityOfZion/neo-privatenet-docker/blob/master/scripts/claim_neo_and_gas.py#L122, and this raises this Exception:

        return json.dumps(context.ToJson(), separators=(',', ':'))
    File "/opt/neo-python/neo/SmartContract/ContractParameterContext.py", line 264, in ToJson
        jsn['items'][shkey] = value.ToJson()
    File "/opt/neo-python/neo/SmartContract/ContractParameterContext.py", line 53, in ToJson
        jsn['parameters'] = [p.ToJson() for p in self.ContractParameters]
    File "/opt/neo-python/neo/SmartContract/ContractParameterContext.py", line 53, in <listcomp>
        jsn['parameters'] = [p.ToJson() for p in self.ContractParameters]
    File "/opt/neo-python/neo/SmartContract/ContractParameterContext.py", line 29, in ToJson
        jsn['type'] = ToName(self.Type)
    File "/opt/neo-python/neo/SmartContract/ContractParameterType.py", line 64, in ToName
        val = int(item[1])
    builtins.TypeError: int() argument must be a string, a bytes-like object or a number, not 'ContractParameterType'

I've been trying to look into it, but am not at all familiar with this code. It seems that [ContractParameterType.py#L64](https://github.com/CityOfZion/neo-python/blob/master/neo/SmartContract/ContractParameterType.py#L64) cannot convert to int because it gets a `ContractParameterType`. 

This behaviour must have been introduced recently, the claim script used to work a week ago.

**Comment by localhuman** [comment]
closed in https://github.com/CityOfZion/neo-python/pull/242
