### ISSUE TITLE
Chain sync error: LevelDBBlockchain:561 header is greater than header index length: ...

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neo-python#250]
There is an error in the current dev branch, when you start syncing with a blockchain and exit before it has synced the full height (eg. at block 599 / 1158), next time you start prompt.py it will show these error outputs continuously:

    [I 180223 15:55:24 LevelDBBlockchain:561] header is greater than header index length: 1158 600

Steps to reproduce:

* Start a [private network container](https://hub.docker.com/r/cityofzion/neo-privatenet/)
* Start `python prompt.py -p`
* Wait until the sync status in the bottom toolbar shows a latest block, when current synced block is anywhere between 0 and the latest (sync is in progress)
* Quit prompt.py
* Start `python prompt.py -p`

At this point, the latest block shown in the bottom toolbar is the last synced one from when you exited prompt.py before, and the above error is shown continuously. New blocks will not be synced, and latest block will not increase. To repeat, just remove `Chains/privnet` and repeat the steps.

**Comment by localhuman** [comment]
Will take a look!

**Comment by localhuman** [comment]
After taking a longer look, I think this may have to do with a very edge case where there's less than 2000 blocks total in the chain.  I can debug more .. but the quick fix is to make sure the starter privnet starts with > 2000 blocks

**Comment by metachris** [comment]
Okay, makes sense. 2000 blocks seems reasonable to start with on the privnet. Thanks for looking into it!

**Comment by vncoelho** [comment]
Hi @localhuman,

in fact, it is quite an important thing to fix for several applications that starts from 0.
Could you please re-check it?

An idea for adjust the OnAddHeader function is:

        headerIncrement = 2000

        if header.Index < headerIncrement:
            headerIncrement = 1
        print("Current header increment %s" % headerIncrement)
        while header.Index - headerIncrement >= self._stored_header_count:
            print("Current header.Index %s" % header.Index)
            ms = StreamManager.GetStream()
            w = BinaryWriter(ms)
            headers_to_write = self._header_index[self._stored_header_count:self._stored_header_count + headerIncrement]
            w.Write2000256List(headers_to_write)
            out = ms.ToArray()
            StreamManager.ReleaseStream(ms)
            with self._db.write_batch() as wb:
                wb.put(DBPrefix.IX_HeaderHashList + self._stored_header_count.to_bytes(4, 'little'), out)

            self._stored_header_count += headerIncrement
            print("Trimming stored header index %s" % self._stored_header_count)
            logger.debug("Trimming stored header index %s" % self._stored_header_count)

        with self._db.write_batch() as wb:
            wb.put(DBPrefix.DATA_Block + hHash, bytes(8) + header.ToArray())
            wb.put(DBPrefix.SYS_CurrentHeader, hHash + header.Index.to_bytes(4, 'little'))


However, you need more than it, there is a part of the code that uses the size of the current header and keeps adding 2000.
even incrementing with +1 is multiples somewhere versus (#index x 2000 -1)

**Comment by vncoelho** [comment]
A brief idea to start the modification can be:

` headerIncrement = 2000

        if header.Index < headerIncrement:
            headerIncrement = 1
        print("Current header increment %s" % headerIncrement)
        while header.Index - headerIncrement >= self._stored_header_count:
            print("Current header.Index %s" % header.Index)
            ms = StreamManager.GetStream()
            w = BinaryWriter(ms)
            headers_to_write = self._header_index[self._stored_header_count:self._stored_header_count + headerIncrement]
            w.Write2000256List(headers_to_write)
            out = ms.ToArray()
            StreamManager.ReleaseStream(ms)
            with self._db.write_batch() as wb:
                wb.put(DBPrefix.IX_HeaderHashList + self._stored_header_count.to_bytes(4, 'little'), out)

            self._stored_header_count += headerIncrement
            print("Trimming stored header index %s" % self._stored_header_count)
            logger.debug("Trimming stored header index %s" % self._stored_header_count)`

However, there are other parts of the code that multiplies the index of the Blockchain when restarting.
Thus, more things should be done.
