### ISSUE TITLE
BinaryReader receives an empty object at test chain block 1042011

### ISSUE THREAD

**Issue by JorritvandenBerg** [CityOfZion/neo-python#251]
The error below occurs both on the master and development branch when initializing with TestNet (Google Drive - ChainTestNet.zip) - 2/21/2018 from awesome-neo. 

<img width="626" alt="screen shot 2018-02-23 at 16 54 38" src="https://user-images.githubusercontent.com/7474467/36613771-d695b6fa-18da-11e8-8b23-25778a7a99af.png">

Currently I am trying to load the test chain with bootstrap.py. Will add an update if this resolves the problem.

**Comment by JorritvandenBerg** [comment]
Unfortunately bootstrapping does not resolve this error

**Comment by localhuman** [comment]
the chains from awesome-neo are for the C# client.  For neo-python you can use the `python bootstrap.py` command.  Make sure before doing that to clean out any relevant directories in your `Chains` directory.
