### ISSUE TITLE
JSON-RPC Api Issues

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neo-python#273]
This issue is meant to track any issues with the json-rpc api. If you find new issues, please either comment here or add a separate issue on GitHub.

Current issues:

- none

Differences to neo-cli:

- C# neo-cli accepts single quotes around object keys, which is not standard JSON. The python json-rpc api only accepts standard json. We keep it like this for now.

See also:

* [#189 JSON RPC API Functionality](https://github.com/CityOfZion/neo-python/issues/189)
* [#233 JsonRpcApi input & output differs from C#](https://github.com/CityOfZion/neo-python/issues/233)

**Comment by dethos** [comment]
Not sure if this issue still serves its purpose. New problems with the RPC usually get a separate issue (plus discussion) of their own.

**Comment by ixje** [comment]
yup, what dethos said. People don't look or find this, they just create new ones. I also think that's better at this point in time
