### ISSUE TITLE
Upgrade version on PyPi

### ISSUE THREAD

**Issue by PJUllrich** [CityOfZion/neo-python#276]
The neo-python version on PyPi is still `0.4.3`, but the latest version on GitHub is `0.4.10`. In order to use `neo-boa` together with `neo-python` one needs version `0.4.10`, which means that one cannot use the PyPi package, but rather have to download the project and install it locally. Would it be possible to upload the latest version to PyPi (and maybe automatize it?)

**Comment by localhuman** [comment]
The version on PyPi shouldn't be there.

Please see this PR: https://github.com/CityOfZion/neo-python/pull/275#issuecomment-369577801
