### ISSUE TITLE
prompt.py not responding to keyboard input after few days

### ISSUE THREAD

**Issue by JorritvandenBerg** [CityOfZion/neo-python#277]
After the following VM errors, prompt.py got stuck in a frozen state:

<img width="944" alt="screen shot 2018-03-01 at 13 52 27" src="https://user-images.githubusercontent.com/7474467/36847166-af2729d2-1d5d-11e8-9ead-158d1c72eed4.png">

**Comment by nickazg** [comment]
Hey @JorritvandenBerg  is there any way to reproduce?

**Comment by ixje** [comment]
Long time since last activity. If the problem still exists, let me know so I can re-open the issue.
