### ISSUE TITLE
What does this project intend to do

### ISSUE THREAD

**Issue by negati-ve** [CityOfZion/neo-python#284]
Hi, I'm fairly new to crypto and NEO and trying to understand what this project intends to do and what can be done with this python port.

quick questions as a newbie:
1. Does this project intend to port NEO project to python for ease of development in the future ? what's the motivation? 
2. Can this project be used to create a fork of the neo project? like a new blockchain with slight modifications to NEO 
3. If this project is forked to create a new blockchain how does one go about making it public? (I know this is a bit off topic.. but appreciate any help)

Thanks in advance :)

**Comment by metachris** [comment]
1) alternative implementation, cross platform, easier to integrate in other systems and programs. More about what this project does is documented in the readme
2) no, at least until consensus mode is implemented
