### ISSUE TITLE
Could not open wallet: Password hash not found in database

### ISSUE THREAD

**Issue by newyue588cc** [CityOfZion/neo-python#289]
Hi，I used the neo-python connection to the test network, but when I opened the neo-cli backup purse file, the following error occurred:
[E 180306 15:37:15 UserWallet:94] Could not build database file is encrypted or is not a database 
[E 180306 15:37:15 UserWallet:330] Could not get key file is encrypted or is not a database 
Could not open wallet: Password hash not found in database

Please help me to solve this problem.Tks.

**Comment by localhuman** [comment]
You can't open a `neo-cli` wallet in `neo-python` directly.  You will need to `export wif` from `neo-cli` then `import wif` into an existing `neo-python` wallet

**Comment by newyue588cc** [comment]
@localhuman The problem has been solved,Thank you for your answer.
