### ISSUE TITLE
[SmartContract.Verifcation.Success] 

### ISSUE THREAD

**Issue by arrangilligan** [CityOfZion/neo-python#297]
please help i dont understand why the smart contract is not going to the blockchain to be executed!

After I import my contract I don´t get [SmartContract.Verifcation.Success] or  [SmartContract.Execution.Success]!?! im using privatenet in an virtual env setup ok. 

below is my screen 
![screenshot from 2018-03-07 21-00-22](https://user-images.githubusercontent.com/11330026/37115151-a1be385c-224a-11e8-8f02-e3bf89302c24.png)

**Comment by arrangilligan** [comment]
ok got it `config sc-events on` helped alot thank you now i can find in with c`ontract search` your the best :) :+1:

**Comment by metachris** [comment]
great :)

**Comment by facadev** [comment]
The following is what it prompts me upon "success", yet I still cannot find the contract by name. Notably, the "name" field in the returned JSON is empty, even though I give it a name upon deployment.

`[SmartContract.Execution.Success][1932] [4a53a2d0410fe181939597af3c920cd3f5e8bd4c] [tx 651e81531152dae2d19f9fbf44fb8e7f97d93097ed0972cd89bbe720811fe73f] ['{\n    "version": 0,\n    "code": {\n        "hash": "0xee071443ecb6a04c840f645ae30cd077605a61e2",\n        "script": "58c56b6a00527ac46a51527ac411436f6e747261637420696e766f6b65642e680f4e656f2e52756e74696d652e4c6f6768164e656f2e53746f726167652e476574436f6e74657874610161515272680f4e656f2e53746f726167652e507574616a00c3077769746e6573739c6424006a51c368184e656f2e52756e74696d652e436865636b5769746e657373616c756661006c7566",\n        "parameters": "0710",\n        "returntype": 1\n    },\n    "name": "",\n    "code_version": "",\n    "author": "",\n    "email": "",\n    "description": "",\n    "properties": {\n        "storage": true,\n        "dynamic_invoke": false\n    }\n}']`
