### ISSUE TITLE
Exception calculating gas consumbed Not supported- Cant get byte array for item

### ISSUE THREAD

**Issue by geek96** [CityOfZion/neo-python#30]
`testinvoke ad60f5039b4fb0b5cd606ab7b77c770ddb2d6cce deploy []`
invoking contract - ImusifyXYZ
checkhing hash...
key is <neo.Wallets.KeyPair.KeyPair object at 0x7fa84ac4e470>
Signing.... ```<neo.Core.TX.InvocationTransaction.InvocationTransaction object at 0x7fa8426d71d0> <neo.Wallets.KeyPair.KeyPair object at 0x7fa84ac4e470>```
private key ```b'AXMzg\x07\xc5r\xc5\x93W\x08\xeb,\xed\x13\x9a\xbf\x11\x87\xbf\xb1O\xc1\x8b\xff\x919<\xfelI'
result is bytearray(b'o\xab\x16\x91\xd2\xa1\xe6h\x1c\xb0m?7\x88\xaa+=\x83_T\xf5\xd7-I\x0fc\x1d\x81\xdd\x08:Zjr\x16\xbb`\xfd\xa1\xff\xd28\x1eW\xfd\xf9/\xbfy@\xd5\xfa\x91\xe61\xc2\x9f\xba\xa8w\xfb\xd9\x00\x18')```
signature bytearray(b'o\xab\x16\x91\xd2\xa1\xe6h\x1c\xb0m?7\x88\xaa+=\x83_T\xf5\xd7-I\x0fc\x1d\x81\xdd\x08:Zjr\x16\xbb`\xfd\xa1\xff\xd28\x1eW\xfd\xf9/\xbfy@\xd5\xfa\x91\xe61\xc2\x9f\xba\xa8w\xfb\xd9\x00\x18')
ADDING SIG!! .... <neo.SmartContract.Contract.Contract object at 0x7fa84431c908> 0 bytearray(b'o\xab\x16\x91\xd2\xa1\xe6h\x1c\xb0m?7\x88\xaa+=\x83_T\xf5\xd7-I\x0fc\x1d\x81\xdd\x08:Zjr\x16\xbb`\xfd\xa1\xff\xd28\x1eW\xfd\xf9/\xbfy@\xd5\xfa\x91\xe61\xc2\x9f\xba\xa8w\xfb\xd9\x00\x18')
ADDING iTEM:: <neo.SmartContract.ContractParameterContext.ContextItem object at 0x7fa8427675f8>
result is True
success is True
going through items b'2102d69b910e9158304eeed1627a06fae7177c257caa8d4106937b9ee50dfea9f39fac'
item parameters??? <neo.SmartContract.ContractParameterContext.ContractParamater object at 0x7fa8428aa748>
going through items b'2102d69b910e9158304eeed1627a06fae7177c257caa8d4106937b9ee50dfea9f39fac'
item parameters??? <neo.SmartContract.ContractParameterContext.ContractParamater object at 0x7fa8428aa748>
GETTING SCRIPTS, item is <neo.SmartContract.ContractParameterContext.ContextItem object at 0x7fa8427675f8>
[Neo.Storage.Get] [Script:ad60f5039b4fb0b5cd606ab7b77c770ddb2d6cce] [b'totalSupply'] -> 0
  ```python File "/usr/lib/python3.5/threading.py", line 882, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "~/venv/lib/python3.5/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "~/venv/lib/python3.5/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
  File "~/venv/lib/python3.5/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "~/venv/lib/python3.5/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "~/venv/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "~/venv/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "prompt.py", line 742, in run
    self.test_invoke_contract(arguments)
  File "prompt.py", line 596, in test_invoke_contract
    tx, fee, results,num_ops = TestInvokeContract(self.Wallet, args)
  File "~/neo-python/neo/Prompt/Commands/Invoke.py", line 139, in TestInvokeContract
    return test_invoke(out, wallet, outputs)
  File "~/neo-python/neo/Prompt/Commands/Invoke.py", line 201, in test_invoke
    success = engine.Execute()
  File "~/neo-python/neo/SmartContract/ApplicationEngine.py", line 163, in Execute
    self.gas_consumed = self.gas_consumed + self.GetPrice() * self.ratio
  File "~/neo-python/neo/SmartContract/ApplicationEngine.py", line 208, in GetPrice
    return self.GetPriceForSysCall()
Exception calculating gas consumbed Not supported- Cant get byte array for item <class 'neo.VM.InteropService.InteropInterface'> <neo.SmartContract.StorageContext.StorageContext object at 0x7fa842773400>```

error executing contract.....
Error testing contract invoke

**Comment by localhuman** [comment]
which branch is this from?

**Comment by geek96** [comment]
**Master** branch. 
Did you required any other information?

**Comment by localhuman** [comment]
How did you compile this contract?

**Comment by geek96** [comment]
I have compiled it on Visual Studio with neo-csharp compiler. 
I am using the `ICO_Template` contract from csharp-example. My deploy function has following lines of code.
```csharp 
        public static bool Deploy()
        {
            byte[] total_supply = Storage.Get(Storage.CurrentContext, "totalSupply");
            if (total_supply.Length != 0) return false;
            Storage.Put(Storage.CurrentContext, Owner, pre_ico_cap);
            Storage.Put(Storage.CurrentContext, "totalSupply", pre_ico_cap);
            Transferred(null, Owner, pre_ico_cap);
            return true;
        }
```

**Comment by localhuman** [comment]
This is a problem with the current neon compiler, which has been fixed in recent changes.  See issues https://github.com/neo-project/neo-compiler/pull/49 and related https://github.com/neo-project/neo-compiler/pull/50

You can build a new version of neon compiler, then re-compile. Or, you could wait for a new release.

**Comment by geek96** [comment]
Thanks.
