### ISSUE TITLE
Exception: DEBUG Leveldb Unavailable b'IO error: ./Chains/debugstorage/LOCK: No such file or directory' 

### ISSUE THREAD

**Issue by arrangilligan** [CityOfZion/neo-python#304]
does anyone know what this is about Leveldb!?!

![screenshot from 2018-03-09 15-29-21](https://user-images.githubusercontent.com/11330026/37212212-b15e4c92-23ae-11e8-893c-b0b4b00fd718.png)

**Comment by metachris** [comment]
Looks like you are running 2 times neo-python. The message at the very top says "you may already be running this process". Only 1 neo-python process can access a database at a time.
