### ISSUE TITLE
Change README.md to README.rst

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neo-python#316]
We should convert README.md to .rst format, because it's reused here and it's fucked up :P https://pypi.python.org/pypi/neo-python

Since the docs are in .rst format, we are all familiar with rst syntax anyway.

**Comment by localhuman** [comment]
I feel like I tried this before for something else.  Perhaps have it autoconverted? https://stackoverflow.com/questions/10718767/have-the-same-readme-both-in-markdown-and-restructuredtext

**Comment by localhuman** [comment]
fixed in https://github.com/CityOfZion/neo-python/pull/317
