### ISSUE TITLE
Update docs.neo.org - neo-python section

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neo-python#323]
http://docs.neo.org/en-us/sc/getting-started-python.html

Instructions are outdated. Replace with current instructions from the neo-python readme, or simply link there and to the docs.

**Comment by localhuman** [comment]
I think this has to be done by the neo team?

**Comment by metachris** [comment]
It can be a PR to the docs repo: https://github.com/neo-project/docs/blob/master/en-us/sc/getting-started-python.md

**Comment by hdespiritu** [comment]
https://github.com/neo-project/docs/pull/448

**Comment by BSathvik** [comment]
Worked on the docs. Waiting on a review.

[neo-project/docs#449](https://github.com/neo-project/docs/pull/449)

**Comment by dethos** [comment]
@metachris Neo Docs now point/link to the`neo-python` documentation. Perhaps this issue could be closed.

**Comment by localhuman** [comment]
👍
