### ISSUE TITLE
P2P joining/bad peer filtering

### ISSUE THREAD

**Issue by localhuman** [CityOfZion/neo-python#325]
Currently `neo-python` only joins the nodes listed in its `protocol.config.json`. 

This change would uncomment line[ 214 of `neo.Network.NeoNode`](https://github.com/CityOfZion/neo-python/blob/master/neo/Network/NeoNode.py#L214) to allow each node to ask for more peers and get information about them and ultimately add them as connected peers.

This functionality was commented out because it ended up allowing lots of bad peers which caused a lot of disconnections and slowdowns.

A better solution would allow this functionality, but filter out unresponsive peers or otherwise bad peers in an intelligent way.

**Comment by nettijoe96** [comment]
[hackathon]
Hi! check out my pull request on this: https://github.com/CityOfZion/neo-python/pull/334

**Comment by ixje** [comment]
@localhuman would it be fair to say this is solved by the following?
https://github.com/CityOfZion/neo-python/blob/ba815b870614d01f9295d934c8dc3a172765e1aa/neo/Network/NodeLeader.py#L18-L25

and 
https://github.com/CityOfZion/neo-python/blob/ba815b870614d01f9295d934c8dc3a172765e1aa/neo/Network/NodeLeader.py#L191-L204

Line #214 that you referred to back then doesn't really make sense in the current tree. 
https://github.com/CityOfZion/neo-python/blob/ba815b870614d01f9295d934c8dc3a172765e1aa/neo/Network/NeoNode.py#L214
btw; if you press `Y` when selecting a line int he code then you'll get a permanent link to the specific commit. Useful for these cases :)

**Comment by localhuman** [comment]
I was thinking of something a bit more robust which might track nodes over time in a persisted state, try them every so often etc to see if they are 'dead', perhaps measure response time to give them a 'quality'.

**Comment by ixje** [comment]
resolved in latest release
