### ISSUE TITLE
getting error on installing requirements.txt with right during setup of neo-python 

### ISSUE THREAD

**Issue by hi0001234d** [CityOfZion/neo-python#359]
### Current behavior
Getting the error ‘struct leveldb::Options’ has no member named ‘max_file_size’ while running the command pip install -r requirements.txt in virtual environment 

### How to reproduce

It happens with latest neo-python clone and CentOS 7.4.1708 right during setup of neo-python  

### environment
- OS: CentOS 7.4.1708
- neo-python version: latest clone from Github np-prompt command not working yet. 
- Python version: 3.5

In between let me know if switching to any stable older branch is wise and could fix this issue. As well as on a side note I've two python running 2.7 and 3.5 and I think 2.7 is partially broken if that has something to do with it.

**Comment by localhuman** [comment]
All versions after `v0.5.0` are only compatible with Python 3.6 and onwards.  If you would like to continue using Python 3.5, you can use any of[ these releases](https://github.com/CityOfZion/neo-python/releases?after=v0.5.0), or check out a tag previous to `v0.5.0`

**Comment by hi0001234d** [comment]
Thank you for your reply. 

Okay, I think its better to move to 3.6 but is it going to be good because the doc here http://docs.neo.org/en-us/sc/getting-started-python.html suggest using 3.5. And they stated on doc specifically that 3.6 is not supported.

**Comment by localhuman** [comment]
Good to know! We have a PR to update the neo.org docs, but we will make sure to get that done sooner rather than later. 

The best documentation for Python will always be http://neo-python.readthedocs.io/

**Comment by hi0001234d** [comment]
Oh okay. And thanks for the link.

**Comment by metachris** [comment]
FYI there is an open PR for the docs.

**Comment by hi0001234d** [comment]
Yeah I got this link http://neo-python.readthedocs.io/. Have one question I'm installing neo-python so do I need to run this command **pip install -r requirements.txt**, it seems that doc says its required to run only during update of neo python but the previous doc I was looking to was mentioning this command during install as well that's why a little bit concerned if its required during install or not

**Comment by metachris** [comment]
It can't hurt to run it. Btw, it's `pip install -e .`

**Comment by hi0001234d** [comment]
Okay thanks
