### ISSUE TITLE
prompt.py: NEP-5 token sending issue

### ISSUE THREAD

**Issue by brianlenz** [CityOfZion/neo-python#363]
### Current behavior

- What is the problem?

Can't send NEP-5 tokens after opening a wallet until you also run the `wallet` command, which has some initialization side effect that is required to send tokens. Specifically, the initialization side effect is happening in `UserWallet.ToJson`. I've spent some time trying to track it down unsuccessfully. Will try to look into it further when I have some more time.

### Expected behavior

- What should be happening?

You should be able to send NEP-5 tokens without running `wallet`.

### How to reproduce

- Please explain the steps to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of this project.

* Open prompt.
* Load a wallet that already has a NEP-5 token loaded in it.
* Run `wallet tkn_send` to try to send the token. It will fail with:

> could not transfer tokens
* Run `wallet`.
* Run `wallet tkn_send` again.
* It will work this time.

**Comment by brianlenz** [comment]
I've had issues running automated transactions from python scripts in the past, as well, and I'm wondering if the root of this issue could be the culprit of those automated transaction issues, as well. I've sometimes had to manually invoke transactions from within prompt when they're otherwise failing through my automated scripts...

**Comment by dethos** [comment]
@brianlenz I was trying to reproduce this issue but I wasn't able to do it, following the steps you provided. Everything went as expected.

**Comment by dethos** [comment]
@brianlenz are you still experiencing this issue?

**Comment by brianlenz** [comment]
@dethos sorry for the delay in getting back to you 🙄 I'll see if I can reproduce it and let you know.

**Comment by brianlenz** [comment]
Yeah, I can't reproduce this issue anymore, so let's close this! Thanks for your persistence in following up on this, @dethos 👍
