### ISSUE TITLE
Error in a private net; Chain database in Chains/privnet is for a different private network than the current container. 

### ISSUE THREAD

**Issue by spider-hand** [CityOfZion/neo-python#385]
Hi, I just tried to start neo-python and I have trouble with setting up private net in a docker container.
I was following  this guy's way. https://medium.com/@nickfujita/neo-dev-environment-setup-tutorial-e495f5364ada
I finished setting up the container but when I put command `neopy`, 
```
Privatenet useragent '/NEO:2.7.4/', nonce: 1143491750
[E 180410 06:51:52 prompt:1044] Chain database in Chains/privnet is for a different private network than the current container. Consider deleting the Chain directory with 'rm -rf /root/.neopython/Chains/privnet/privnet*'.
root@c0a7d9680785:/neo-python#
```
this error occured.  Why is this error occured and how can I fix it? The error is still happening even if I deleted the container once. `docker rm -f neo-privatenet`
I'm currently installing Docker on Windows10pro and using command line.

**Comment by metachris** [comment]
I'll check...

**Comment by metachris** [comment]
Thanks for reporting! I actually made some kind of error in the latest CoZ/neo-privatenet Docker image. Fixed it and pushed a new image. Please update with `docker pull cityofzion/neo-privatenet`.

Thanks a lot for reporting!
