### ISSUE TITLE
Few module or imports within are not found

### ISSUE THREAD

**Issue by hi0001234d** [CityOfZion/neo-python#388]
### Current behavior

So I'd been trying https://github.com/nickazg/neo-fund/blob/master/neo-fund-py/neo-fund-prompt.py blockchain middleware of NeoFund project. The issue is related to few neo module not found or some imports within it is not found. And since other module in neo are found properly I think the neo blockchain setup properly in virtual environment and actually I've been building and invoking test contracts so environment is set but the problem is with below imports. 

ModuleNotFoundError: No module named 'neo.Wallets.KeyPair'
ModuleNotFoundError: No module named 'neo.Prompt.Commands.Withdraw'
ImportError: cannot import name 'construct_contract_withdrawal'
from neo.Prompt.Notify import SubscribeNotifications

I'd commented first 3 imports because that was not used by script but the last import SubscribeNotifications is used in script so I think I need to solve this error

### How to reproduce

Run the script https://github.com/nickazg/neo-fund/blob/master/neo-fund-py/neo-fund-prompt.py in the environment similar to below

### environment

OS: CentOS 7.4.1708
neo-python version: v0.6.7
Python version: 3.6

In between on a side note I've two python running 2.7 and 3.6 and I think 2.7 is partially broken but I think that's not relevant here

**Comment by metachris** [comment]
Yeah the reason for the error you are seeing is that neo-fund-prompt.py uses a very old neo-python version. Those imports are now part of `neocore`:

    from neocore.KeyPair import KeyPair

You should open an issue at the neo-fund repository, and ask for a requirements file that you can install the neo-python version that it is working with.

**Comment by hi0001234d** [comment]
Thanks, got it! I will give try to that for sure 

Can you suggest me any recent dApp with wallet and REST API implementation. In between let me know if there is any other competition like this https://medium.com/proof-of-working/coz-first-dapps-competition-dapp-review-3a6b284afaef from where I can learn more insights

**Comment by hi0001234d** [comment]
NVM got it https://cityofzion.io/dapps/2/, wondering when is the 3rd?
