### ISSUE TITLE
Commit() of changed storage items happens regardless of invocation fault state

### ISSUE THREAD

**Issue by hal0x2328** [CityOfZion/neo-python#393]
### Current behavior
After a contract invocation, any changed storage items are committed to leveldb even if the contract execution ends in a fault state

### Expected behavior
If a contract ends in a fault state, any changed storage items for that invocation should be discarded

### How to reproduce

Create a contract with more than 10 Storage.Put syscalls, and relay that transaction sending zero GAS with it. After execution, the storage for the contract will contain the last Put value before running out of the 10 free GAS, instead of the original storage pre-invoke state

### Your environment
All environments

### Additional details
The `Commit()` call that erroneously changes the storage after a fault happens here: https://github.com/CityOfZion/neo-python/blob/53d13b1561e8c48a79fc6f98ed04dca231d759d9/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py#L781

Normally the commits of an invocation should happen in this code, which will not be run in case of a fault: https://github.com/CityOfZion/neo-python/blob/53d13b1561e8c48a79fc6f98ed04dca231d759d9/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py#L738

The problem seems to be with the scope of the `storages` object in `Persist()`.  In the csharp code at https://github.com/neo-project/neo/blob/11d8db11568d9eadeeb86c5b8c21a1d3937e0912/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.cs#L578 it has the `using` keyword which seemingly makes a copy of `storages` that is local to that block and doesn't impact the main storages object declared at the top of the `Persist()` function. So when a contract faults, it skips the `Commit()` as it should and that inner `storages` copy is disposed of once the execution of that invocation is finished. 

In the neo-python code, the main `storages` object in the `Persist()` function is modified in each invoke instead of a copy local to that invocation, so when the final `storages.Commit()` call is completed for the entire block, all the storage keys for faulted invocations end up being updated.

**Comment by localhuman** [comment]
I think the solution is to remove this line: https://github.com/CityOfZion/neo-python/blob/master/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py#L784

That's my intuition, though I need to write some tests to confirm 😉
