### ISSUE TITLE
Chain database in Chains/privnet is for a different private network than the current containe

### ISSUE THREAD

**Issue by miro-ka** [CityOfZion/neo-python#405]
### Current behavior

I'm not able to start neopy after I have stopped docker. If I follow the instructions, the problem remains (not privnet* files are present).

<img width="622" alt="screen shot 2018-04-28 at 19 35 02" src="https://user-images.githubusercontent.com/1301154/39399275-4a18b68c-4b1b-11e8-8fd9-81425f53a11e.png">

### Environment

- OS: OSX 10.13.4
- docker installed with: 
`docker run -d --name neo-privatenet -p 20333-20336:20333-20336/tcp -p 30333-30336:30333-30336/tcp -v "$(pwd)":/neo-python/smartContracts cityofzion/neo-privatenet`

**Comment by metachris** [comment]
Didn't mean to close the issue. Please let us know if this helped, then we can close it.

**Comment by miro-ka** [comment]
fantastic,..thanks a lot!

**Comment by metachris** [comment]
Looking at it again, the error was that previously the wrong command to remove the old chain was provided, it included 2x "privnet". The latest release has it fixed :-) also my command above should work
