### ISSUE TITLE
ModuleNotFoundError:  No module named 'boa.blockchain'

### ISSUE THREAD

**Issue by hi0001234d** [CityOfZion/neo-python#407]
I'm trying to build a smart contract https://github.com/ixje/precognition-dapp-coz2/blob/master/middleware/examples/prediction/sc/event.py from an dApp2 project but it seems like something seems changed in latest version of neo-python. 

However when I build the sample_3.py contract from doc http://neo-python.readthedocs.io/en/latest/neo/SmartContract/smartcontracts.html#smart-contracts-within-the-prompt, it works fine but not the one from dApp2 project

**Comment by localhuman** [comment]
`boa.blockchain.vm` was refactored to `boa.interop`

**Comment by hi0001234d** [comment]
Ohh okay thanks so much
