### ISSUE TITLE
ModuleNotFoundError: No module named 'boa.code.builtins'

### ISSUE THREAD

**Issue by hi0001234d** [CityOfZion/neo-python#409]
Issue similar to one as in https://github.com/CityOfZion/neo-python/issues/407, I'd been looking at change log but not found any info on it or may be I don't know how to look for it. But I assume that module name is changed

**Comment by metachris** [comment]
Try `boa.builtins` instead of `boa.code.builtins`

**Comment by hi0001234d** [comment]
One more error 
`ModuleNotFoundError: No module named 'storage'`

**Comment by hi0001234d** [comment]
Hold on I think its local module
