### ISSUE TITLE
Unicode error at create new wallet

### ISSUE THREAD

**Issue by DrMartiner** [CityOfZion/neo-python#414]
### Current behavior

"Unicode-objects must be encoded before hashing" at creating new wallet

### Expected behavior

I expected new protected wallet

### How to reproduce

```python
from neo.Wallets.Wallet import Wallet
wallet = Wallet('ico.wallet', 'long-password-100500', True)
```

```
Traceback (most recent call last):
  File "/soft/pydevd.py", line 1668, in <module>
    main()
  File "/soft/pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/soft/pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/soft/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/app/wllet.py", line 3, in <module>
    wallet = Wallet('ico.wallet', 'e96282e86d4ee0e5affab77a4bbaf163e5b8815e', True)
  File "/venv/python3.6/site-packages/neo/Wallets/Wallet.py", line 95, in __init__
    passwordHash = hashlib.sha256(passwordKey).digest()
TypeError: Unicode-objects must be encoded before hashing
```

### Your environment

Let us know in what environment you're running into the issue:

- OS: OSX
- neo-python version: 0.6.9
- Python version: 3.6.4

**Comment by metachris** [comment]
You need to convert a password to an aes key first. Do:

    from neo.Wallets.Wallet import Wallet
    from neo.Wallets.utils import to_aes_key
    password_key = to_aes_key("my password")
    wallet = Wallet('ico.wallet', password_key, True)

then it will work

**Comment by DrMartiner** [comment]
@metachris thanks a lot

**Comment by DrMartiner** [comment]
@metachris btw, what should I do to save my new wallet in file ```ico.wallet``` ?

**Comment by metachris** [comment]
The question is what you want to do. Use it with neo-python? Then you should use `UserWallet`. Just create a private and public key? Then you could just store the data manually.
