### ISSUE TITLE
Question: JSON-RPC and wallet

### ISSUE THREAD

**Issue by kornrunner** [CityOfZion/neo-python#428]
Hi,

This actually isn't an issue, but rather a question on usage. I've tried to find it in docs and existing issues, but I've failed, so I apologize upfront if I've missed something.

I've initially used `neo-cli` and it's RPC API. I've got an application written in PHP that's using JSON RPC to communicate with neo node and do stuff. However, recently I've wanted to do something with smart contracts, and neo-cli isn't supporting them in JSON RPC API yet, so I've stumbled upon your project.

What I'm looking for is: how can I open my wallet when running `np-api-server`? I've managed to open the wallet by using `np-prompt`, but since I need RPC endpoint open as well for contracts, and I need my funds available for smart contrancts - how can I acheive this?

Thank you!

**Comment by dethos** [comment]
I'm not sure this is possible at the moment. According to this issue, https://github.com/CityOfZion/neo-python/issues/189, some of the RPC methods that require the open wallet aren't implemented yet.

**Comment by metachris** [comment]
Which RPC methods in particular would you like to use?

**Comment by kornrunner** [comment]
I was hoping for `sendtoaddress` which I reckon I'd need unlocked wallet.

**Comment by dethos** [comment]
I'm currently working on a PR that might solve this issue and allow us to add the missing methods, that depend on an open wallet. 

I should have the first draft ready in the next few days.

**Comment by metachris** [comment]
@kornrunner is this helping you, and do you have any more reason for this issue to stay open?

**Comment by kornrunner** [comment]
It looks like this is it. I'll still have to check it out, but I'll close this one and open a new one if anything is out of order.

Thank you very much!
