### ISSUE TITLE
No getAccountState method?

### ISSUE THREAD

**Issue by j4ys0n** [CityOfZion/neo-python#429]
### Current behavior

- What is the problem?
There doesn't seem to be a `getAccountState` method on `np-api-server`
Error: `node.getAccountState is not a function`

### Expected behavior

- What should be happening?
I should be able to call `getAccountState("account")` from `neo-api-js`

### How to reproduce

- Please explain the steps to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of this project.
- Build with [Dockerfile](https://github.com/CityOfZion/neo-python/blob/master/docker/Dockerfile).
- Install `neo-api` in node.js application
- run:
```javascript
    var node = neo.node('http://neo-pyton-ip:port');
    node.getAccountState('NEO-ADDRESS-HERE').then((result) => {
      res.send(result);
    })
    .catch((error) => {
      res.send(error);
    });
```
- result: `node.getAccountState is not a function`
- when running `res.send(Object.keys(node))` this is the response:
```javascript
[
    "$post",
    "serviceName",
    "serviceBaseUrl",
    "servicePollInterval",
    "baseUrl",
    "protocolClient",
    "poll",
    "getBalance",
    "getLastBlockHash",
    "getBlockByHeight",
    "getBlockCount",
    "getBlockHashByHeight",
    "getConnectionCount",
    "getVersion",
    "getRawMemPool",
    "getRawTransaction",
    "getTxOut"
]
```
### Your environment

Let us know in what environment you're running into the issue:

- OS: (Windows version/Linux distro/OSX version) 
Docker container on Ubuntu.
- neo-python version: (hint: use `np-prompt --version`)
neo-python v0.6.9
- Python version: (hint: `python -V`)
Docker container is installing Python 3.6, so you need to run `python3 -V`         
Python 3.6.3

**Comment by dethos** [comment]
@j4ys0n this doesn't seem to be an issue with `neo-python` but perhaps with `neo-api-js`. The RPC method [`accountgetstate`](http://docs.neo.org/en-us/node/cli/api/getaccountstate.html) is working as described in the documentation.

do you have any other information that might indicate it is a problem with `neo-python`?

**Comment by j4ys0n** [comment]
`neo-api-js` has the methods.. https://github.com/CityOfZion/neo-api-js/blob/master/src/neo/services/node/index.js

**Comment by ixje** [comment]
`neo-python` has the handler for `getaccountstate`
https://github.com/CityOfZion/neo-python/blob/311df80dc1d6cc3f2d61b0aab43591b479886a6e/neo/api/JSONRPC/JsonRpcApi.py#L122-L132

Given that the list of supported RPC functions you posted above misses the huge list of supported functions below (just browse the code linked above) I'd like to think the problem resides on the JS side, not on `neo-python`'s side. 

```
getaccountstate
getassetstate
getbestblockhash
getblock
getblockhash
getblocksysfee
getstorage
invoke
invokefunction
invokescript
sendrawtransaction
submitblock
validateaddress
getpeers
```

**Comment by metachris** [comment]
Yes, if the error is `node.getAccountState is not a function`, then `getAccountState` is not implemented in the `node` object, so it's an issue on the JS side of things
