### ISSUE TITLE
incompatible wallets between neo-cli and neo-python

### ISSUE THREAD

**Issue by sirpy** [CityOfZion/neo-python#432]
i've created wallets using both neo-cli and neo-python when trying to open the python wallet with neo-cli i get "error" and when trying to open the neo-cli wallet with python i get 
"[E 180524 12:20:34 UserWallet:94] Could not build database table "account" already exists 
[E 180524 12:20:34 UserWallet:336] Could not get key no such column: t1.Id 
Could not open wallet: Password hash not found in database"

**Comment by metachris** [comment]
are you opening a `.db` or `.json` wallet file? guess both would not work right now, but just wondering if the old `.db` format is still in use.

**Comment by sirpy** [comment]
db3.
python isnt able to open json at all

**Comment by ixje** [comment]
To the best of my knowledge there has never been the intend to have shared wallet db's. Each client can have there own depending on the clients implementation. However, to easily transfer from one client to another there is the [NEP-6 standard](https://github.com/neo-project/proposals/blob/master/nep-6.mediawiki) for importing wallets. Unfortunately this is not yet supported as seen by the open issue #118 

For now if you want to switch you'll have to export your WIF's (what people call private keys) and import them in a new or exisitng `neo-python` wallet. type `help` on the console for seeing the commands to create a wallet and import a WIF.
