### ISSUE TITLE
Rest API initializing double Chains and notifications going to .neopython

### ISSUE THREAD

**Issue by vncoelho** [CityOfZion/neo-python#434]
### Current behavior

API rest is starting the chains and notifications twice, even when --datadir /root/.XXX/ is called.

In addition, notifications are not being reported by the API, the JSON is returning always empty.

[I 180525 02:48:58 utils:42] Notification/Block [] 183
[] is the empty notification and 183 was the requested block
[I 180525 02:45:04 _observer:131] "172.19.0.1" - - [25/May/2018:02:45:03 +0000] "GET /v1/notifications/block/184 HTTP/1.1" 200 119 "-" "Mozilla/5.0 (X11; Linux x86_64;

Even debugging from inside RestApi.py, it was seeing that the notification were empty before being sent.
Thus, the error may be in the function notifications = self.notif.get_by_block(block)

- What is the problem?

- Include a screenshot if it makes sense.
![image](https://user-images.githubusercontent.com/17395762/40522056-4ce0d14e-5fa5-11e8-9e1b-9d8f2d93c529.png)

### Expected behavior
- What should be happening?
- Include a screenshot if it makes sense.

### How to reproduce

- Please explain the steps to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of this project.

### Your environment

Let us know in what environment you're running into the issue:

- OS: (Windows version/Linux distro/OSX version) 
- neo-python version: (hint: use `np-prompt --version`)
- Python version: (hint: `python -V`)

Version 0.69 or 0.7 Development

IDEA FOR FIXING:

settings.py
    DATA_DIR_PATH = PATH_USER_DATA

Perhaps, PATH_USER_DATA should not be used anymore after the initialization.
    def set_data_dir(self, path):
        if path == '.':
            self.DATA_DIR_PATH = os.getcwd()
        else:
            self.DATA_DIR_PATH = path

I do not know, something like that... :dagger:

**Comment by metachris** [comment]
What's the exact command you use to start the rest api (with all arguments)?

**Comment by vncoelho** [comment]
Hi, @metachris,

    My fault, I did not follow all the steps for the issue, I apologize.

    In fact, there are **two problems**.

    1) The first one is the screenshot, initiallized with the command: 
 /neo-python-rpc-rest/neo/bin/api_server.py --datadir /root/.neo-python-rpc-rest/ --privnet --port-rest 8080

   2) The other one took our team **4 hour of debugging** yesterday! 
        * We tried to simply initialize two prompts (because we need the wallet ON-THE-FLY for being called). However, the same `--datadir` command does not move the logs (prompt.log and .prompt.py.history).

       * We tried to hardcode in the neo Settings and nothings worked. It seems that the standard (.neopython) was inserted in some binary.

   What do your recommend?

   Furthermore, if you have any other any idea for letting the wallets ready for being called, please, let us know.

Best regards,

**Comment by metachris** [comment]
Hey @vncoelho 

I'm not sure I can follow. The api-server does not use `prompt.log` or `prompt.py.history`. These files are only used/created with `prompt.py`

Btw, You should start the api server with `np-api-server` instead of directly referencing the Python file.

I tried reproducing the datadir problem and indeed there was an error that I most likely fixed with #436. Can you please double-check?

**Comment by vncoelho** [comment]
![image](https://user-images.githubusercontent.com/17395762/40662869-df21dbe4-632d-11e8-8775-5d60b011b960.png)


I just reproduced, @metachris. It was easy to check.
The problem is that even with --datadir the /.neopython is still being created and the prompt.py and history being redirected to there.

I think that the configuration was inserted some binary. Because we already tried to hard code several things.

**Comment by metachris** [comment]
`np-prompt` does not create `prompt.log` or `prompt.py.history`, only `np-prompt` creates those files. They have been in that directory from before. 

Have you actually used the branch with my latest code from the PR? I believe you are not using the code from my PR.

For me it works:

    # np-prompt -p --datadir /root/.test
    [I 180529 13:53:36 Settings:245] Data directory /root/.test does not yet exist. Creating...
    Privatenet useragent '/NEO:2.7.4/', nonce: 1554563778
    [I 180529 13:53:36 Settings:295] Created 'Chains' directory at /root/.test/Chains
    [I 180529 13:53:36 LevelDBBlockchain:114] Created Blockchain DB at /root/.test/Chains/privnet
    [I 180529 13:53:36 NotificationDB:73] Created Notification DB At /root/.test/Chains/privnet_notif
    NEO cli. Type 'help' to get started

    neo>

As you can see, no mention of the `.neopython` directory.

**Comment by vncoelho** [comment]
No, they were not. I deleted the folder two times, Metachris.

**Comment by vncoelho** [comment]
Sorry, I confused this issue.

There are two points.
1) The logs of np-prompt have this problem. I just deleted them now and np-promp still sends them to .neopython. Something in the Binary could be happenning, as I said

the 2) is the api-server, it is also calling .neopython and then changing the chain folder.

But, perhaps, can be the same problem.

**Comment by metachris** [comment]
It's not in the binary, but set here: https://github.com/CityOfZion/neo-python/blob/development/neo/bin/prompt.py#L53

Proposing a pull request in a few minutes to put the prompt log and history into the custom `datadir`

**Comment by vncoelho** [comment]
Could be this.

There is also something else, Metachris.

    3) the RPC and Rest are still with problems when run together.

    4) the Rest is not publishing the notifications, we tried the 0.6.9 version and now the 0.7. 
     The notifications are empty even in the auxiliary vector, I mean,  even when we check the vector that came from Block.Notification, not only in the API outside.

**Comment by metachris** [comment]
See #437 for a proposal to store prompt log and history files in a custom `datadir`.

Not sure what you mean with (3) and (4) exactly, please open a new ticket for those issues with an exact description and steps to reproduce.

**Comment by vncoelho** [comment]
Thanks for copying this issue into https://github.com/CityOfZion/neo-python/pull/437

I think you can deal with it from now on.
