### ISSUE TITLE
Address should not be calculated automatically in neo-python prompt.py

### ISSUE THREAD

**Issue by igormcoelho** [CityOfZion/neo-python#439]
### Current behavior

- What is the problem?
prompt.py is changing my strings, depending on what it "thinks" is my intention.

This is the test code:
```
using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Services.Neo;
using System;
using System.Numerics;
namespace NeoContract1
{
    public class Contract1 : SmartContract
    {
        public static bool Main(string op, object[] arg)
        {
            Runtime.Notify(op);
            string arg1 = (string)arg[0];
            Runtime.Notify(arg1);
            return true;
        }
    }
}
```

I will put three different invocations (the second is strange because it interprets my string as I wanted to convert it to scripthash).

testinvoke 292313cbb1e0c663527c893d64182ddf87f450ff teste1 ["teste2"]
b'teste1'
b'teste2'

testinvoke 292313cbb1e0c663527c893d64182ddf87f450ff teste1 ["AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y"]
b'teste1'
b'#\xba\'\x03\xc52c\xe8\xd6\xe5"\xdc2 39\xdc\xd8\xee\xe9'

testinvoke 292313cbb1e0c663527c893d64182ddf87f450ff teste1 ["AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y_"]
b'teste1'
b'AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y_'

- Include a screenshot if it makes sense.

### Expected behavior

testinvoke 292313cbb1e0c663527c893d64182ddf87f450ff teste1 ["AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y"]
b'teste1'
b'AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y'

- What should be happening?
prompt.py shouldn't interfere in input string. If user wants address to be translated to scripthash, it must use an explicit function for it:

testinvoke 292313cbb1e0c663527c893d64182ddf87f450ff teste1 [ AddressToScriptHash("AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y")]
b'teste1'
b'#\xba\'\x03\xc52c\xe8\xd6\xe5"\xdc2 39\xdc\xd8\xee\xe9'

I know this is verbose, and perhaps many people prefer things "automated", but it can limit the testing abilities of the user (like my case, where I simply cannot pass a regular address string).

- Include a screenshot if it makes sense.

### How to reproduce

- Please explain the steps to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of this project.

### Your environment

Let us know in what environment you're running into the issue:
Eco platform: https://neocompiler.io

- OS: (Windows version/Linux distro/OSX version) 
- neo-python version: (hint: use `np-prompt --version`)
- Python version: (hint: `python -V`)

**Comment by jseagrave21** [comment]
Was this issue address in PR #483 ? cc @localhuman @ixje

**Comment by ixje** [comment]
Arguably. Let's see what @igormcoelho thinks of that PR in relation to his issue report.

**Comment by ixje** [comment]
ping @igormcoelho 
will close in 2 weeks if no reaction

**Comment by igormcoelho** [comment]
Oh! sorry for the delay!
It looks like it has been addressed: "Adds ability to not parse address strings such as AeV59NyZtgj5AMQ7vY6yhr2MRvcfFeLWSb when inputting to smart contract by passing the --no-parse flag"
Congratulations!

**Comment by ixje** [comment]
Thanks!
