### ISSUE TITLE
Feature request: Save raw blocks to allow offline resync

### ISSUE THREAD

**Issue by ThomasLobker** [CityOfZion/neo-python#441]
### Current behavior

- Whenever a bug is fixed or something that would require a resync to fix the current data in the backend, `neo-python` needs to redownload all blocks.

### Expected behavior

- Because the already fetched raw blocks should never change, they can be safely stored on disk and used again. Whenever a users needs to or wants to resync, `neo-python` could use the cached blocks instead of downloading them from other nodes.

`neo-cli` has something like this where you can safe the blocks as an `acc` file.

**Comment by ixje** [comment]
Just to make sure you're aware; neo-python has a feature to [bootstrap](https://github.com/CityOfZion/neo-python#bootstrapping-the-blockchain). This is basically a zip'ed copy of the blockchain + notification db so you don't even have to process the blocks anymore. It's also updated every 1-2 weeks.

**Comment by ThomasLobker** [comment]
> This is basically a zip'ed copy of the blockchain + notification db so you don't even have to process the blocks anymore.

Yes I'm aware and this is actually exactly my point. I've had multiple occasions where I found that the processed data was faulty, so processing the raw blocks again with an updated version of `neo-python` would be necessary. I personally think it's best practice to let node operators maintain their own backups and snapshots and not rely on centralized pre-processed bootstrap files. No offence, but `neo-python` has currently no way to verify the integrity of a bootstrap file.

I would be okay too with a feature where `neo-python` can verfiy the integrity of the bootstrap file in the background. This would probably be a much bigger change though.

**Comment by ixje** [comment]
Good point on the integrity (and obviously no offence taken) This issue of course also exists with the `.acc` file provided by NEO. It's all trust based. 

I've thought a bit about other ways of bootstrapping in the past where consensus nodes sign off on certain data to build trust without having to process everything yourself. That idea originated when thinking about pruning large chains (something we'll likely want to support in a distant future) but the solution can potentially overlap with your request. If you'd like we can brainstorm a bit on Discord on a bigger scale than just for `neo-python`?

**Comment by dethos** [comment]
This issue seem to have been solved with the new `export`/`import` features. Perhaps it is time to close it.
