### ISSUE TITLE
COULD NOT EXECUTE OP (127): Not supported b'\x7f' SUBSTR

### ISSUE THREAD

**Issue by ediopia** [CityOfZion/neo-python#450]
When I try to slice integer array, it returns error

<img width="382" alt="screen shot 2018-06-02 at 7 17 46 pm" src="https://user-images.githubusercontent.com/6670368/40882527-cbdc6b7a-6699-11e8-8377-7d633150f8e5.png">
<img width="939" alt="screen shot 2018-06-02 at 7 17 18 pm" src="https://user-images.githubusercontent.com/6670368/40882528-d020f8ea-6699-11e8-8cd8-4d551691b1a0.png">

**Comment by localhuman** [comment]
At the current time, list manipulation (building slices) is supported for strings and byte arrays, but not for lists.

https://neo-boa.readthedocs.io/en/latest/overview.html#what-parts-of-python-are-supported
