### ISSUE TITLE
Installation error for specific packages 

### ISSUE THREAD

**Issue by sozhan95** [CityOfZion/neo-python#460]
### Current behavior

- What is the problem?
Few packages failed to install while doing a pip install for neo-python 

----------------------------------------
  Failed building wheel for mpmath
  Running setup.py clean for mpmath
  Running setup.py bdist_wheel for mmh3 ... error
  Complete output from command /home/sozhan/myneo/venv/bin/python3.6 -u -c "import setuptools, tokenize;file='/tmp/pip-build-htezv68i/mmh3/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" bdist_wheel -d /tmp/tmpc4gy1g3cpip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for mmh3
  Running setup.py clean for mmh3
  Running setup.py bdist_wheel for pymitter ... error
  Complete output from command /home/sozhan/myneo/venv/bin/python3.6 -u -c "import setuptools, tokenize;file='/tmp/pip-build-htezv68i/pymitter/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" bdist_wheel -d /tmp/tmpq4it8l14pip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for pymitter
  Running setup.py clean for pymitter
  Running setup.py bdist_wheel for memory-profiler ... error
  Complete output from command /home/sozhan/myneo/venv/bin/python3.6 -u -c "import setuptools, tokenize;file='/tmp/pip-build-htezv68i/memory-profiler/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" bdist_wheel -d /tmp/tmp4ok_t7cupip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  
### Expected behavior

- What should be happening?
pip install should ideally install all the packages 

### Your environment

- OS:Ubuntu 18.04

- Python version: Python v3.6

**Comment by metachris** [comment]
What's the exact command you used to install neo-python, which failed?
