### ISSUE TITLE
new wallet support in api_server does not invoke wallet.ProcessBlocks()

### ISSUE THREAD

**Issue by dfletcher** [CityOfZion/neo-python#479]
### Current behavior

Wallet support was recently added to the API server in #459 but the opened wallet does not stay synchronized with the blockchain.

### Expected behavior

When launching a similar feature in neo/bin/prompt.py, a thread is started which periodically calls `wallet.ProcessBlocks()` to synchronize the wallet with the chain. api_server.py never does this, it should be added.

The way I fixed this locally was just to make wallet a global variable and call `wallet.ProcessBlocks()` from `custom_background_code()`. Possibly a better long term fix is to launch it in it's own thread.

### How to reproduce

Send coin to wallet, check balance - it will always show zero because the wallet does not stay synced.

### Environment

- OS: Ubuntu 16.04
- neo-python version: neo-python v0.7.2-dev
- Python version: Python 3.6.5

**Comment by metachris** [comment]
Thanks for the report! finally got around to implementing it. Should work like in this PR: #493

**Comment by metachris** [comment]
fixed fixed in current dev branch
