### ISSUE TITLE
Wrong encoding of input

### ISSUE THREAD

**Issue by Sindbag** [CityOfZion/neo-python#481]
Here: https://github.com/CityOfZion/neo-python/blob/f570ce99302033b6276e338ee5043449b118ba70/neo/VM/ScriptBuilder.py#L106

If input is string but could be safely encoded as bytes array it would be treated as number and encoded to number and then hexlified.

For example b'test' is encoded to bytes 74 65 73 74, all of them are numbers and it is treaded as number, whilst b'test.' is encoded to 74657374 2E, which is not treated as number.

I am not sure about that mechanic, but I had tested it on my contract  by deserialization of resulting transaction and finding that out. Seems to be bug only in np-prompt, not the whole neo.

**Comment by ixje** [comment]
Please comment if this is not solved in the latest release and we can re-open
