### ISSUE TITLE
Issues with np-prompt in the latest version 0.7.2

### ISSUE THREAD

**Issue by jonathanlimwj** [CityOfZion/neo-python#485]
### Current behavior
After doing a 'np-prompt -p` , it shows an error "ImportError: cannot import name 'byte_string'"
What is the problem?

    Traceback (most recent call last):
    File "/home/tmo/Documents/neo-python/venv/bin/np-prompt", line 11, in <module>
        load_entry_point('neo-python', 'console_scripts', 'np-prompt')()
    File "/home/tmo/Documents/neo-python/venv/lib/python3.6/site-packages/pkg_resources/init.py", line 561, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
    File "/home/tmo/Documents/neo-python/venv/lib/python3.6/site-packages/pkg_resources/init.py", line 2631, in load_entry_point
        return ep.load()
    File "/home/tmo/Documents/neo-python/venv/lib/python3.6/site-packages/pkg_resources/init.py", line 2291, in load
        return self.resolve()
    File "/home/tmo/Documents/neo-python/venv/lib/python3.6/site-packages/pkg_resources/init.py", line 2297, in resolve
        module = import(self.module_name, fromlist=['name'], level=0)
    File "/home/tmo/Documents/neo-python/neo/bin/prompt.py", line 28, in <module>
        from neo.Implementations.Wallets.peewee.UserWallet import UserWallet
    File "/home/tmo/Documents/neo-python/neo/Implementations/Wallets/peewee/UserWallet.py", line 8, in <module>
        from neo.Wallets.Wallet import Wallet
    File "/home/tmo/Documents/neo-python/neo/Wallets/Wallet.py", line 13, in <module>
        from Crypto.Cipher import AES
    File "/home/tmo/Documents/neo-python/venv/lib/python3.6/site-packages/Crypto/Cipher/init.py", line 3, in <module>
        from Crypto.Cipher._mode_ecb import _create_ecb_cipher
    File "/home/tmo/Documents/neo-python/venv/lib/python3.6/site-packages/Crypto/Cipher/_mode_ecb.py", line 29, in <module>
        from Crypto.Util._raw_api import (load_pycryptodome_raw_lib,
    File "/home/tmo/Documents/neo-python/venv/lib/python3.6/site-packages/Crypto/Util/_raw_api.py", line 32, in <module>
        from Crypto.Util.py3compat import byte_string
    ImportError: cannot import name 'byte_string'

### Expected behavior
It should show neo-python running
- What should be happening?

### How to reproduce

For ubuntu:

    sudo apt install docker.io
    sudo docker pull cityofzion/neo-privatenet
    sudo docker run --rm -d --name neo-privatenet -p 20333-20336:20333-20336/tcp -p 30333-30336:30333-30336/tcp cityofzion/neo-privatenet
    sudo apt install software-properties-common python-software-properties
    sudo add-apt-repository ppa:deadsnakes/ppa
    sudo apt update
    sudo apt install python3.6 python3.6-dev python3.6-venv python3-pip libleveldb-dev libssl-dev g++
    cd /usr/local/src # or ~/Documents or wherever you want to install neo-python
    git clone https://github.com/CityOfZion/neo-python.git
    cd neo-python
    python3.6 -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
    pip install -e .
    np-prompt -p

For mac os:
1. Install Hebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)

2. Download docker (community edition)
https://store.docker.com/editions/community/docker-ce-desktop-mac
Register account
Docker pull cityofzion/neo-privatenet

3. Install python
Brew install python

4. Install leveldb 
Brew install leveldb

5. Make directory 
Mkdir neosc && cd neosc

6. Git clone repositories                                                         
 Git clone https://github.com/CityOfZion/neo-python.git
Cd neo-python
7. Create virtual env
python3.6 -m venv venv
source venv/bin/activate
8. Install dependencies
pip install -e .

9. Run docker container
docker run --rm -d --name neo-privatenet -p 20333-20336:20333-20336/tcp -p 30333-30336:30333-30336/tcp cityofzion/neo-privatenet

11. execute.                         
  np-prompt -p

### Your environment

Let us know in what environment you're running into the issue:

- OS: OSX -x64
- neo-python version: 0.7.2
- Python version: 3.6.5

**Comment by localhuman** [comment]
There's currently a conflict with two crypto libraries. next release gets rid of `pycrypto` altogether.  Until then, you can try:
``` 
pip uninstall pycrypto
pip uninstall pycryptodome
pip install pycryptodome
```

**Comment by jseagrave21** [comment]
Try pip install pycryptodome==3.6.1

When I used pip install pycryptodome, it install 3.6.3 which is not compatible with neo-python.

**Comment by TimRi91** [comment]
pip uninstall pycrypto
pip uninstall pycryptodome
pip install pycryptodome

but don't forget to install the pycrypto again

**Comment by jseagrave21** [comment]
Do you need pycrypto if you have pycryptodome? I was able to run neo successfully by just following the instructions from @localhuman.

**Comment by markremi** [comment]
Looks like I'm seeing the same issue (even after following instructions from @localhuman unfortunately). 

- pycrpto 2.6.1
- pycrptodome 3.6.1
- python 3.6.5
- OS: OSX -x64

**Comment by localhuman** [comment]
pycrypto has been totally removed in v0.7.3, so this issue should be resolved.

**Comment by Raj-Dave368** [comment]
> Looks like I'm seeing the same issue (even after following instructions from @localhuman unfortunately). However, for whatever reason, the following worked for me. Seems like `easy_install` installs more libs than `pip` install:
> 
> `pip uninstall pycrypto`
> `easy_install pycrypto`
> 
> 👍

om namah shivay✊🏻omNS omNS
Thanks so much maro BholiyoBaBo maro nath maro hun

**Comment by Pei116** [comment]
I had to uninstall `pycrypto` and install `pycryptodome` only
