### ISSUE TITLE
error during intallation 

### ISSUE THREAD

**Issue by EgorXor** [CityOfZion/neo-python#495]
i am trying to download neoblockchain on my windows server via python3.6
. I am alredy installed it now ,but  fail to implement my smart contract because of bad connection . now i am reinstall it and made all steps of installation for windows .pip install neo-python , got the following error 
![1](https://user-images.githubusercontent.com/27733019/42349190-80aa4dd6-80b4-11e8-9ef9-49fed0164ee5.png)

why this error happens ?

**Comment by jseagrave21** [comment]
I had several errors like this occur for me during my installation process. Are you sure you have all the dependencies installed per the readme? And you have python 3.6 installed?

**Comment by metachris** [comment]
The error is saying you need MS Visual C++ 14 and provides a link. Have you installed that already?

**Comment by ixje** [comment]
Let us know if the issue still exists after you install the MS Visual C++ 14 requirements and we can reopen it.
