### ISSUE TITLE
PR #49 is not backward compatible

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neo-python#50]
PR #49 is nice but not backward compatible. It requires `ApplicationConfiguration.themes` in the configuration json file. If it is not existing it fails with: 

```
Traceback (most recent call last):
  File "prompt.py", line 823, in <module>
    settings.setup(args.config)
  File "/Users/chris/Projects/chris/neo/neo-python/neo/Settings.py", line 79, in setup
    self.token_style = config['themes'][config['theme']]
KeyError: 'themes'
```

I would suggest to check if this key exists and if not use the old default.

**Comment by localhuman** [comment]
Should be resolved in 8da5e2c
