### ISSUE TITLE
Console EventHub not there

### ISSUE THREAD

**Issue by TimRi91** [CityOfZion/neo-python#500]
### Current behavior

After running my docker container of my neo-privatenet and successfully importing my Smart-Contract, i want to test the return-values by testinvoking the Sc. But i don't see any Eventhub-Loggings.
![image](https://user-images.githubusercontent.com/40432499/42514384-9b65b2ca-8459-11e8-85d6-9d97bef78ec8.png)

### Expected behavior

There should be some Loggings, like in this example:
![image](https://user-images.githubusercontent.com/40432499/42514372-930cae8a-8459-11e8-9590-e53355a81bd3.png)

### Your environment

Let us know in what environment you're running into the issue:

- OS: Ubuntu
- neo-python version: 0.6.6
- Python version: 3.6

**Comment by jseagrave21** [comment]
I am assuming you were able to test invoke the SC with the "build" command. Besides that, to view events maybe try "np-prompt -p -v".

**Comment by ixje** [comment]
type `config sc-events on `

**Comment by TimRi91** [comment]
I needed to execute `np-prompt -p -v` to see the eventhub.

**Comment by ixje** [comment]
That also works. The command I posted allows you to turn it on/off while neo-python is already running. The `np-prompt -v` does so in the startup phase
