### ISSUE TITLE
smart-contract event decode  

### ISSUE THREAD

**Issue by TimRi91** [CityOfZion/neo-python#502]
### Current behavior

smart-contract.py 

Event on calling `Storage.Put`
get:
`Could not persist block 'str' object has no attribute 'decode'` 
for the command line:
`logger.info("- payload part 1: %s", event.event_payload[0].decode("utf-8"))`

content of `event.event_payload[0]` is `b'\x01 -> bytearray(b'Tim')`

![image](https://user-images.githubusercontent.com/40432499/42566955-942028f6-8508-11e8-86e7-3fe6227f43d8.png)

### Your environment

- OS: Ubuntu
- neo-python version: 0.6.6
- Python version: 3.6

**Comment by ixje** [comment]
Can you provide code and steps to reproduce?

**Comment by ixje** [comment]
actually looking closer at your screenshot I now realise that `event_payload[0]` does not hold
 `b'\x01 -> bytearray(b'Tim')` but it holds `"b'\\x01 -> bytearray(b'Tim')"`. Notice the quotes around the bytearray, that means it's a string and then yes the error makes sense. string does not have a `decode()` method
