### ISSUE TITLE
[Travis-ci] Enable fixture file caching to reduce test time

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo-python#510]
### Current behavior
Currently when travis does its magic, it downloads the [fixture file](https://github.com/CityOfZion/neo-python/blob/cc4da934d3afc2ad46e1deb98ce638f0afd157bc/neo/Utils/BlockchainFixtureTestCase.py#L14) a second time when executing this line:
https://github.com/CityOfZion/neo-python/blob/cc4da934d3afc2ad46e1deb98ce638f0afd157bc/.travis.yml#L24

### Expected behavior
We should configure travis-ci to cache the fixture file because that file is big and unnecessary adds minutes of download time to the whole test cycle.

### How to reproduce

re-run any build 

### Your environment

n/a

**Comment by ixje** [comment]
@metachris Travis seems to be your baby. Would you mind looking into this ? :)

**Comment by metachris** [comment]
I'll take a look! 👍
