### ISSUE TITLE
Add support for incoming P2P connections

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo-python#522]
### Current behavior
Afaik; currently only `neo-python` can setup new connections to a node, but a node cannot connect to `neo-python`.

to privnet/C# node
```
Eriks-Air: erik$ nc 192.168.1.100 20333
��version'��L��U[mO��U
                      /NEO:2.7.4/�^C
```
to neo-python
```
Eriks-Air: erik$ nc 192.168.1.100 20338
Eriks-Air:mitmproxy erik$
```

### Expected behavior
neo-python should also accept incoming connections.

### How to reproduce

point any node to `neo-python` or try to netcat to it (see above).

**Comment by jseagrave21** [comment]
@ixje Hey, I am testing the new dev branch as an RPC node and am receiving a lot of error messages. This occurs the most frequently:
```
Traceback (most recent call last):
  File "/mnt/c/users/seagrave/neo/neo-python-dev/neo/Network/NeoNode.py", line 213, in CheckDataReceived
    self.MessageReceived(message)
  File "/mnt/c/users/seagrave/neo/neo-python-dev/neo/Network/NeoNode.py", line 257, in MessageReceived
    self.HandleGetHeadersMessageReceived(m.Payload)
  File "/mnt/c/users/seagrave/neo/neo-python-dev/neo/Network/NeoNode.py", line 510, in HandleGetHeadersMessageReceived
    self.SendSerializedMessage(Message('headers', HeadersPayload(headers=headers)))
  File "/mnt/c/users/seagrave/neo/neo-python-dev/neo/Network/Message.py", line 44, in __init__
    payload = binascii.unhexlify(Helper.ToArray(payload))
  File "/mnt/c/users/seagrave/neo/neo-python-dev/neo/Core/Helper.py", line 77, in ToArray
    value.Serialize(writer)
  File "/mnt/c/users/seagrave/neo/neo-python-dev/neo/Network/Payloads/HeadersPayload.py", line 44, in Serialize
    writer.WriteSerializableArray(self.Headers)
  File "/mnt/c/users/seagrave/neo/neo-python-dev/venv/lib/python3.6/site-packages/neocore/IO/BinaryWriter.py", line 408, in WriteSerializableArray
    item.Serialize(self)
AttributeError: 'NoneType' object has no attribute 'Serialize'
Traceback (most recent call last):
  File "/mnt/c/users/seagrave/neo/neo-python-dev/neo/Network/NeoNode.py", line 213, in CheckDataReceived
    self.MessageReceived(message)
  File "/mnt/c/users/seagrave/neo/neo-python-dev/neo/Network/NeoNode.py", line 247, in MessageReceived
    self.SendPeerInfo()
  File "/mnt/c/users/seagrave/neo/neo-python-dev/neo/Network/NeoNode.py", line 357, in SendPeerInfo
    self.Log("Peer list %s " % list(map(lambda p: p.ToString(), peerlist)))
  File "/mnt/c/users/seagrave/neo/neo-python-dev/neo/Network/NeoNode.py", line 357, in <lambda>
    self.Log("Peer list %s " % list(map(lambda p: p.ToString(), peerlist)))
AttributeError: 'NoneType' object has no attribute 'ToString'
```
Is this expected?

**Comment by jseagrave21** [comment]
There are also several other errors, which I can share if they are desirable.

**Comment by jseagrave21** [comment]
Additionally, HappyNodes wasn't seeing me as active. I shut down my server and set "AcceptIncomingPeers" to `false` and my server seems to be working now.

**Comment by ixje** [comment]
Thanks! Interesting that this wasn't caught before. Localhuman ran the build for a week 🤔 
I fixed it, but curious what other errors you're seeing before I push the fix

As for RPC. Unless you've set `RPCPort` to be equal to `NodePort` then I don't see how they would conflict but I will investigate

**Comment by localhuman** [comment]
I think the issue is I didn't run my tests of the node as an RPC node.

**Comment by ixje** [comment]
I'm actually seeing that when I allow it to connect to peers + allow incoming peers that I can't request the version. So my tests have always been "disable connecting to seedlist to make sure data retrieved is actually coming from neo-python". That works fine. However, both `listenTCP` and `connectTCP` on the same port seems to not work for the `listenTCP` side. If I change the `listenTCP` port to something else it's responsive instantly. However, even according to this 3 year old blog it's not something that technically infeasible http://www.codeghar.com/blog/echo-server-and-client-with-twisted.html (see the "Add Factory" code snippet about half way the page)

**Comment by penlite** [comment]
@ixje do you mean "getversion" RPC call?

**Comment by ixje** [comment]
@penlite no. When you connect to a node over the P2P port the handshake sequence is started which begins with sending  a network [Message](http://docs.neo.org/en-us/network/network-protocol.html#network-message) with the command value `'version'`.

**Comment by jseagrave21** [comment]
@ixje  Okay. I am running it again. It seems like it is working better. However, there are still several errors.

Seems to occur most frequently when starting:
```
[E 180829 22:34:05 NeoNode:488] Could not deserialize: Invalid UInt: data length 0 != specified num_bytes 32 neo.Network.Payloads.GetBlocksPayload.GetBlocksPayload
```

Occurs frequently:
```
[E 180829 22:38:28 NeoNode:473] Could not deserialize: Invalid format neo.Core.Block.Block
Traceback (most recent call last):
  File "/mnt/c/users/seagrave/neo/neo-python-dev/neo/Network/NeoNode.py", line 213, in CheckDataReceived
    self.MessageReceived(message)
  File "/mnt/c/users/seagrave/neo/neo-python-dev/neo/Network/NeoNode.py", line 255, in MessageReceived
    self.HandleBlockReceived(m.Payload)
  File "/mnt/c/users/seagrave/neo/neo-python-dev/neo/Network/NeoNode.py", line 475, in HandleBlockReceived
    blockhash = block.Hash.ToBytes()
AttributeError: 'NoneType' object has no attribute 'Hash'
```

Occurs frequently:
```
[C 180829 22:41:10 _observer:131]
    Traceback (most recent call last):
      File "/mnt/c/users/seagrave/neo/neo-python-dev/venv/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
        current.result = callback(current.result, *args, **kw)
      File "/mnt/c/users/seagrave/neo/neo-python-dev/venv/lib/python3.7/site-packages/twisted/internet/task.py", line 236, in eb
        d.errback(failure)
    AttributeError: 'NoneType' object has no attribute 'errback'
```

Also, it seems like my server takes longer to update its chain. Normally, it is never "behind" but, sometimes I do see it one block behind and sometime more.

**Comment by ixje** [comment]
Can you provide a bit more details, I'm trying to reproduce.
- What specific branch/commit are you running ? and with which cli-arguments do you start your server?
- Which network are you syncing on?
- Between (roughly) what block range do these errors occur?

I've synced a couple thousand blocks of Mainnet starting from Block 2603557 (this is what the mainnet bootstrap file starts at) with no errors.

**Comment by jseagrave21** [comment]
I ran it on the latest development branch.
Started with `$ np-api-server --mainnet --port-rpc 10332 --port-rest 80 --maxpeers 200`
I'm not sure which network.
They occurred frequently during normal operation.

**Comment by jseagrave21** [comment]
It could be the bad block issue with my server perhaps? I am waiting for a clean bootstrap file to rebuild my  node.

**Comment by ixje** [comment]
I've run your command for 2 hours. 1 hour with `AcceptIncomingPeers` set to `true` and 1 hour with it set to `false`. I've had 0 errors thus far so it's kind of hard debugging for me

**Comment by jseagrave21** [comment]
Okay. I will test again after I update my server. I am going to wait for a new chain. Do you know if your local node has any corrupt blocks?

**Comment by ixje** [comment]
I don't know to be fair. I just bootstrapped from `Main2600xxx` and I wasn't really present when all the bad block discussions happened so I don't now the numbers

**Comment by jseagrave21** [comment]
Okay, when you run your node is it observable? Do you have connected peers and HappyNodes indicates P2P is `true`?

**Comment by ixje** [comment]
in 0.7.8 release
