### ISSUE TITLE
Neo suddenly stopped syncing

### ISSUE THREAD

**Issue by AnkitRathore175** [CityOfZion/neo-python#551]
### Current behavior

- What is the problem?
It's showing below status
Aug 13 14:09:04 ip-172-31-9-247 dewneodaemon.sh[9452]: [I 180813 14:09:04 _observer:131] Starting factory <neo.Network.NodeLeader.NeoClientFactory object at 0x7f8fb0910748>
Aug 13 14:09:04 ip-172-31-9-247 dewneodaemon.sh[9452]: [I 180813 14:09:04 _observer:131] "18.220.227.83" - - [13/Aug/2018:14:09:04 +0000] "POST / HTTP/1.1" 200 48 "-" "Ruby"
Aug 13 14:09:05 ip-172-31-9-247 dewneodaemon.sh[9452]: [I 180813 14:09:05 _observer:131] Starting factory <neo.Network.NodeLeader.NeoClientFactory object at 0x7f8fb0918da0>
Aug 13 14:09:06 ip-172-31-9-247 dewneodaemon.sh[9452]: [I 180813 14:09:06 _observer:131] Stopping factory <neo.Network.NodeLeader.NeoClientFactory object at 0x7f8fcd494dd8>
Aug 13 14:09:06 ip-172-31-9-247 dewneodaemon.sh[9452]: [I 180813 14:09:06 _observer:131] Starting factory <neo.Network.NodeLeader.NeoClientFactory object at 0x7f8fb014b9e8>
Aug 13 14:09:07 ip-172-31-9-247 dewneodaemon.sh[9452]: [I 180813 14:09:07 _observer:131] Starting factory <neo.Network.NodeLeader.NeoClientFactory object at 0x7f8fb0159908>
Aug 13 14:09:07 ip-172-31-9-247 dewneodaemon.sh[9452]: [I 180813 14:09:07 _observer:131] Stopping factory <neo.Network.NodeLeader.NeoClientFactory object at 0x7f8fb0910748>
Aug 13 14:09:08 ip-172-31-9-247 dewneodaemon.sh[9452]: [I 180813 14:09:08 _observer:131] Stopping factory <neo.Network.NodeLeader.NeoClientFactory object at 0x7f8fb0918da0>
Aug 13 14:09:08 ip-172-31-9-247 dewneodaemon.sh[9452]: [I 180813 14:09:08 _observer:131] Starting factory <neo.Network.NodeLeader.NeoClientFactory object at 0x7f8fb0e47da0>
Aug 13 14:09:08 ip-172-31-9-247 dewneodaemon.sh[9452]: [I 180813 14:09:08 _observer:131] Stopping factory <neo.Network.NodeLeader.NeoClientFactory object at 0x7f8fb0e47da0>
Aug 13 14:09:09 ip-172-31-9-247 dewneodaemon.sh[9452]: [I 180813 14:09:09 _observer:131] Starting factory <neo.Network.NodeLeader.NeoClientFactory object at 0x7f8fb0918ef0>
Aug 13 14:09:09 ip-172-31-9-247 dewneodaemon.sh[9452]: [I 180813 14:09:09 _observer:131] Stopping factory <neo.Network.NodeLeader.NeoClientFactory object at 0x7f8fb0918ef0>
- Include a screenshot if it makes sense.

### Expected behavior
 It's stuck on 2603301 / 2613999
And no progress since last 5 days

- What should be happening?
- Include a screenshot if it makes sense.

### How to reproduce

- Please explain the steps to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of this project.

### Your environment
running on mainnet

Let us know in what environment you're running into the issue:

- OS: (Windows version/Linux distro/OSX version) 
ubuntu
- neo-python version: (hint: use `np-prompt --version`)
neo-python v0.7.2-dev
- Python version: (hint: `python -V`)
Python 2.7.12
And
Python3.6

**Comment by ixje** [comment]
Please update to the latest `neo-python` version. If it still persists let us know and we can re-open the issue.

**Comment by AnkitRathore175** [comment]
I tried with latest pull from development branch, Now i'm getting below error
![image](https://user-images.githubusercontent.com/38749604/44201428-d3fb5480-a166-11e8-8a8a-2efb30aa5482.png)

**Comment by metachris** [comment]
Did you update all dependencies?

**Comment by AnkitRathore175** [comment]
Dependencies like?
I just tried below-

![image](https://user-images.githubusercontent.com/38749604/44202213-ef675f00-a168-11e8-8b8a-aeb1b6bd77d7.png)

**Comment by ixje** [comment]
Please do a `pip install requirements.txt'. The new version has updated requirements you do not meet.
