### ISSUE TITLE
The prompt command "send" is not working with "asset name"

### ISSUE THREAD

**Issue by dauTT** [CityOfZion/neo-python#557]
### Current behavior
The `send` command is working only for **assetId**.
- What is the problem?

This `send` command is not working for **asset name**

```send {assetId or name} {address} {amount} (--from-addr={addr}) (--fee={priority_fee})```

- Include a screenshot if it makes sense.
![image](https://user-images.githubusercontent.com/30392990/44290037-20ce5080-a277-11e8-85b2-2db0f18645a6.png)

### Expected behavior

- What should be happening? The `send` command should work if we use the **asset name**
- Include a screenshot if it makes sense.

### How to reproduce
See image above

- Please explain the steps to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of this project.

See image above

### Your environment

Let us know in what environment you're running into the issue:

- OS: Ubuntu 18.x
- neo-python version: v0.7.5
- Python version: 3.6.5

**Comment by jseagrave21** [comment]
@dauTT I think this is because Neo-python is looking for 'gas'. I followed the code back to prompt/utils [here](https://github.com/CityOfZion/neo-python/blob/ba815b870614d01f9295d934c8dc3a172765e1aa/neo/Prompt/Utils.py#L79)
If you send 'gas' does it work?

**Comment by jseagrave21** [comment]
I confirmed on my privatenet as shown below:

```
neo> send gas AVM2PsCnwYY9WtWBGqD3Ujzq2e3QSKgFTK 100
sending with fee: 0.0
[Password]> ***
[I 180817 20:10:03 Transaction:615] Verifying transaction: b'3cd9757f8b82ef9ab576eac8fd16f24ca607eee9c42e86869d8c4b48d8843e00'
Relayed Tx: 3cd9757f8b82ef9ab576eac8fd16f24ca607eee9c42e86869d8c4b48d8843e00
neo> tx 3cd9757f8b82ef9ab576eac8fd16f24ca607eee9c42e86869d8c4b48d8843e00
{
    "txid": "0x3cd9757f8b82ef9ab576eac8fd16f24ca607eee9c42e86869d8c4b48d8843e00",
    "size": 283,
    "type": "ContractTransaction",
    "version": 0,
    "attributes": [
        {
            "usage": 32,
            "data": "23ba2703c53263e8d6e522dc32203339dcd8eee9"
        }
    ],
    "vout": [
        {
            "n": 0,
            "asset": "0x602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7",
            "value": "100",
            "address": "AVM2PsCnwYY9WtWBGqD3Ujzq2e3QSKgFTK"
        },
        {
            "n": 1,
            "asset": "0x602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7",
            "value": "25974",
            "address": "AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y"
        }
    ],
    "vin": [
        {
            "txid": "aa2051096e7be45ed991279a1a4c2678eb886690829a2729f4caa82192ff7f34",
            "vout": 0
        }
    ],
    "sys_fee": "0",
    "net_fee": "0",
    "scripts": [
        {
            "invocation": "40702bfe61df43d7d451d84aa1e68d910a1f2e222688902e6a0193c7399626a96827ef4fd0101cc42cbbd5cfdc4db64482e41116e607e8d28c81dedc529a08e0b5",
            "verification": "21031a6c6fbbdf02ca351745fa86b9ba5a9452d785ac4f7fc2b7548ca2a46c4fcf4aac"
        }
    ],
    "height": 9363,
    "unspents": [
        {
            "n": 0,
            "asset": "0x602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7",
            "value": "100",
            "address": "AVM2PsCnwYY9WtWBGqD3Ujzq2e3QSKgFTK"
        },
        {
            "n": 1,
            "asset": "0x602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7",
            "value": "25974",
            "address": "AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y"
        }
    ]
}
```

**Comment by jseagrave21** [comment]
Would it be a good idea to add "neogas" as an accepted assetId to a avoid this confusion in the future? @ixje

**Comment by ixje** [comment]
- please start following the issue guidelines and test issues you report with the latest version before reporting. We have a limited group of people contributing and it can save us time if we don't have to dig into and understand issues that have actually already been solved in the latest available version. Thank you.
- As for not working,  you need to specify `neo` or `gas`

@jseagrave21 I don't think `neogas` would be a good addition as in the current state it is never referred to like that within `neo-python` but thanks for the suggestion.

**Comment by dauTT** [comment]
Thanks @ixje for your advice and explanation. I got confuse because the name is `NEOGas` and not `gas` but it seems that there are some convention in place tha I am not aware of. 
![image](https://user-images.githubusercontent.com/30392990/44429835-22f71e80-a599-11e8-947d-910a2d9bcdbf.png)

**Comment by ixje** [comment]
I stand corrected on the 'never referred to as neogas'. I've honestly never seen it spelled out like that before.

**Comment by jseagrave21** [comment]
In NEO GUI I think it is referred to as NEOGas as well. That being said, could you comment again on my earlier question about adding it as an accepted assetId? I would be happy to do it.
