### ISSUE TITLE
RPC-Call getrawtransaction response differs to C# CLI response

### ISSUE THREAD

**Issue by wy** [CityOfZion/neo-python#575]
### Current behavior
Transaction references in the VIN's of the transaction response are missing the 0x prefix.
Tested on latest Python version 0.7.7 and also latest NEO CLI V2.8.0

```
 "vin": [
                {
                    "txid": "8d3cb1d3191014b21312698e33742d0cd7548bb95ca52ad51758a9f3b1e5e2bf",
                    "vout": 0
                },
                {
                    "txid": "b93453a52f0806809003b69a4b1e2d3278b5950f1cdb3a6176b563dd108f92c8",
                    "vout": 40
                }
            ],
```

### Expected behavior

Expect:
```
 "vin": [
                {
                    "txid": "0x8d3cb1d3191014b21312698e33742d0cd7548bb95ca52ad51758a9f3b1e5e2bf",
                    "vout": 0
                },
                {
                    "txid": "0xb93453a52f0806809003b69a4b1e2d3278b5950f1cdb3a6176b563dd108f92c8",
                    "vout": 40
                }
            ],
```

### How to reproduce

Python:
https://http://happynodes.f27.ventures/unconfirmedtxinfo/24/83b710d92074b4141e4b1a8e50c559fa15e31ee1bb066f4d75d294be2a6ed57e

NEO-CLI
https://http://happynodes.f27.ventures/unconfirmedtxinfo/445/83b710d92074b4141e4b1a8e50c559fa15e31ee1bb066f4d75d294be2a6ed57e

Or just do the standard JSON-RPC call 
```
{
        "jsonrpc": "2.0",
        "method": "getrawtransaction",
        "params": ["0x83b710d92074b4141e4b1a8e50c559fa15e31ee1bb066f4d75d294be2a6ed57e",1],
        "id": 3
}
```

### Your environment

Any - tested on multiple using Happynodes to test production nodes on Python and NEO-CLI.

**Comment by wy** [comment]
Is this scheduled for release @ixje? Unfortunately Im going to have to keep my polyfill live until the whole network moves onto this version..

**Comment by ixje** [comment]
@wy we don't really have a fixed release schedule. It's a bit up to feeling (how long ago was last release, how severe are issues currently fixed in `dev` branch, etc)
