### ISSUE TITLE
Implement NEP8

### ISSUE THREAD

**Issue by localhuman** [CityOfZion/neo-python#585]
neo-python should be ready to support NEP8 as soon as it is on Testnet/Mainnet.  

Relevant changes in neo-vm here: https://github.com/neo-project/neo-vm/pull/39

**Comment by ixje** [comment]
what is NEP8? I see many open PR's for NEPs that are not officially numbered yet, so I'm not sure which one is going to be NEP8.

**Comment by localhuman** [comment]
Updated issue with changes.

**Comment by deanpress** [comment]
@ixje  debugged my smart contract and noticed the C# compiler already utilizes NEP-8. So many contracts built in C# can not be invoked in neo-python atm.

**Comment by ixje** [comment]
I'm going to look into this on Monday.

**Comment by localhuman** [comment]
FWIW I don't believe NEP8 is on Mainnet CN yet.

**Comment by ixje** [comment]
also requires https://github.com/neo-project/neo/commit/0de8b8867326405265e3daa24128269e33d914de
