### ISSUE TITLE
change the default testmode of the run function of the smartcontract virtual machine

### ISSUE THREAD

**Issue by edwardz246003** [CityOfZion/neo-python#609]
In the smartcontract virtual machine, the default testmode of run function is True. This will make the RPC invokescript with infinite gas. It should be change to false.

  
https://github.com/CityOfZion/neo-python/blob/978f77922247d2d85c63dfe8db66e856fcb56582/neo/SmartContract/ApplicationEngine.py#L409

**Comment by ixje** [comment]
thanks!

**Comment by ixje** [comment]
fixed by https://github.com/CityOfZion/neo-python/pull/581
specifically:
https://github.com/CityOfZion/neo-python/blob/978f77922247d2d85c63dfe8db66e856fcb56582/neo/SmartContract/ApplicationEngine.py#L239-L242
