### ISSUE TITLE
How to use neo smart contract invocation from websites like ethereum has web3

### ISSUE THREAD

**Issue by novaknole** [CityOfZion/neo-python#617]
### Current behavior
- Are you using the latest available version? If not, first update and verify the problem still exists.
- What is the problem?
- Include a screenshot if it makes sense.

### Expected behavior

- What should be happening?
- Include a screenshot if it makes sense.

### How to reproduce

- Please explain the steps to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of this project.

### Your environment

Let us know in what environment you're running into the issue:

- OS: (Windows version/Linux distro/OSX version) 
- neo-python version: (hint: use `np-prompt --version`)
- Python version: (hint: `python -V`)

**Comment by metachris** [comment]
The software that is similar to web3 is https://github.com/CityOfZion/NeoLink

Alternatively you can build a custom backend with eg. neo-python and talk with that from the frontend. See the examples for more info in that regard: https://github.com/CityOfZion/neo-python/tree/master/examples
