### ISSUE TITLE
Create python wrapper for neo-hypervm

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo-python#620]
[neo-hypervm](https://github.com/CityOfZion/neo-hypervm) is a high performance implementation of the VM written in C++. It would be nice if we can choose to run the high performance VM in certain conditions (or just when hosting an RPC server).

There's a C# wrapper in the project that you can potentially use as reference if you're not familiar with the VM implementation. Either a `ctypes` solution or CPython extension would do depending on the performance gap between the two. We prefer highest performance, but if the difference is minimal then maintainability comes first (which would mean `ctypes`)

**Comment by jseagrave21** [comment]
I will try to contribute to this. Sounds pretty cool.

**Comment by ixje** [comment]
Just a friendly warning, this is a potentially tough issue if you don't understand the current VM design. My advise would be to start there

**Comment by ixje** [comment]
Closing due to focus on NEO3. Also neo-hypervm hasn't been updated in a long time and isn't expected to be any time soon.
