### ISSUE TITLE
[Feature] Add docs

### ISSUE THREAD

**Issue by localhuman** [CityOfZion/neo-python#63]
Add actual documentation to the project.

**Comment by localhuman** [comment]
- Add in docstrings to all methods/modules etc
- Fill in docstrings with more than boilerplate
- Create sphinx documentation
- Publish to [readthedocs.io](url)

**Comment by ixje** [comment]
Any good document that shows how the docstrings should look for sphinx compatibility? I find there website a bit messy. Perhaps some samples how to document function parameters, return type would be nice.

**Comment by metachris** [comment]
Here is an example:

* Docstrings: https://github.com/metachris/logzero/blob/master/logzero/__init__.py#L379
* Generated docs: https://logzero.readthedocs.io/en/latest/#i-logzero-logfile

**Comment by ixje** [comment]
I started converting #74 to [rST format](https://www.python.org/dev/peps/pep-0287/) as requested by @localhuman [here](https://github.com/CityOfZion/neo-python/pull/73#issuecomment-342985048). Unfortunately also that standard leaves room for interpretation / free will. Before having to edit everything a 3rd time I'd like to get to an agreement on how to document the following:

- multiple return types
- exceptions
- notes

### multiple return types

Example with current [Sphinx Napoleon format](https://pypi.python.org/pypi/sphinxcontrib-napoleon):
```
"""
Change the password used to protect the private key.

    Args:
        password_old (str): the current password used to encrypt the private key.
        password_new (str): the new to be used password to encrypt the private key.

    Returns:
        bool: False, if the old password does not match the current saved password.
        None: If successfully changed the password.

"""

```

**Attempt 1**:
```
        :return: False, if the old password does not match the current saved password. None, If succesfully changed the password.
        :rtype: bool, None
```

**Attempt 2** (suggested [here](https://stackoverflow.com/a/39761518/3869515)):
Note: this drops the `:rtype:`
```
    :return: 
        bool False if the old password does not match the current saved password. 
        None None If successfully changed the password.
```

### Exception documentation
Example:
```
        """
        Retrieve the script_hash from an address.

        Args:
            address (str): a base58 encoded address.

        Raises:
            ValuesError: if an invalid address is supplied or the coin version is incorrect.
            Exception: if the address checksum fails.

        Returns:
            UInt160: script hash

        """
```

**PyCharm format:**
> :raises: :exc:`ExceptionType`
```
   :raises: :exc: `ValueError` if an invalid address is supplied or the coin version is incorrect.
   :raises: :exc: `Exception` if the address checksum fails.
```
Note that I'm uncertain here if I should repeat `:raises:` and if it's ok to add the description behind it.

**Sphynx doc** [example](http://www.sphinx-doc.org/en/stable/domains.html)
```
   :raises ValueError: if an invalid address is supplied or the coin version is incorrect.
   :raises Exception: if the address checksum fails.
```

### Notes
Current:
```
"""
Add a watch only address to the wallet.
  
Args:
    script_hash (UInt160): a bytearray (len 20) representing the public key.

Returns:
    None
 
Note:
    Prints a warning to the console if the address already exists in the wallet.
 
"""
```

Attempt (ok?)
```
        """
        Add a watch only address to the wallet.

        :param script_hash: a bytearray (len 20) representing the public key.
        :type script_hash: UInt160
        .. note:: Prints a warning to the console if the address already exists in the wallet.
        :return:
        """
```

**Comment by localhuman** [comment]
This is by no means finished, but a WIP here: http://neo-python.readthedocs.io/en/latest/index.html

Currently working out of the `feature-docs` branch

**Comment by ixje** [comment]
It's probably good to say we settled on using Google's docstring notation and no longer die rST format discussed just above.

**Comment by localhuman** [comment]
This is complete, though further documentation would never hurt.
