### ISSUE TITLE
TODO: Run neo-python in ARM CPU architecture using Docker

### ISSUE THREAD

**Issue by nunojusto** [CityOfZion/neo-python#636]
### Current behavior
Currently we only have docker containers to run in x86/x64 CPU

### Expected behavior
Run a normal docker container in ARM architecture CPU like the Raspberry Pi board and others.

### Objective
Build a Dockerfile that can build a container and installed seamlessly

**Comment by metachris** [comment]
What is the issue here in particular? You can run the current Docker image on the Raspberry Pi, no? What kind of change in the Dockerfile do you think about?

**Comment by nunojusto** [comment]
No, the current docker don't build directly on ARM/Raspbian. We need some extra dependencies.
I have done lots of tries and installed many things. I can get the smaller list of dependencies I can and post here.
Maybe those dependencies are not exclusive of ARM raspbian and we can add them to the default dockerfile(s) we currently have. That way the same Dockerfile will build on all x86/x64 and arch.

If you feel this is not important right now, just close this issue and we can move on. No problem :)

**Comment by metachris** [comment]
What are you trying to do -- run the neo-python Docker image on a Raspberry, or build it there? I don't see a real advantage of building the image on a Pi.

**Comment by nunojusto** [comment]
What I've done was trying to run the normal docker image on a Pi. First you need to build it there (the image itself).
So, after that, the container runs, but neo-python doesn't, by lack of dependencies.
Then, I've fiddled around and installed many things inside the running container. And now neo-python prompt is working without problem.
In resume, I will do it again and see what really helped the lack of dependencies and propose 1 or 2 scenarios:
1- The normal Dockerfile can accept those new things without interfering with x86/x64 arch and we can use the same file for all.
2- We need a separated Dockerfile for ARM/raspbian.

The goal is obvious, the first scenario.
My question to the community is: Should I bother spending time with this? Just because I don't want to spend time for a PR that is not needed.

**Comment by metachris** [comment]
As discussed in chat, this can be a fun hobby project, but not prioritised. Closing this issue. @nunojusto if you want to spend a few hours on this as hobby/side project, feel free to :)
