### ISSUE TITLE
/v1/tokens endpoint returns wrong script hash

### ISSUE THREAD

**Issue by corck** [CityOfZion/neo-python#647]
### Current behavior
I am working on a new token and compiling it in neo-python console and testing it, everything works out fine. My new code is compiled and the functionality is executed. When NeoScan's token sync is trying to sync the token it fails because of the code script hash, as it is not unique. Investigating into the problem I figured out that neo-pythons REST API returns, and probably saves the wrong script hash, it actually uses the script hash of the already existing Nex Token.

![Screenshot of new token](https://user-images.githubusercontent.com/58671/46455275-8d12fe00-c7aa-11e8-8962-36ef6149ba35.png)

![Screenshot of returned token of /v1/tokens](https://user-images.githubusercontent.com/58671/46455290-9d2add80-c7aa-11e8-9f82-2f1dcbae6156.png)

I'm running neo-local with neo-python 0.8.

### Expected behavior

/v1/tokens should return the script hash of screenshot 1 in contract -> code -> hash

### How to reproduce

Run the latest neo-local. Use the nex neo-ico-template and modify it. Compile and build the contract. Compare the script hash of /v1/tokens to the one you got when compiling the contract

### Your environment

Linux docker images of neo-local. 
neo-python v0.8.0
Python 3.6.3

**Comment by ixje** [comment]
FYI; Should be in dev branch.

**Comment by corck** [comment]
Fixed now, will close.
