### ISSUE TITLE
[Feature] Implement NEP 2 for wallet

### ISSUE THREAD

**Issue by localhuman** [CityOfZion/neo-python#65]
Implement NEP2 standard for passphrase protection outlined here:

https://github.com/neo-project/proposals/blob/master/nep-2.mediawiki

**Comment by metachris** [comment]
@ixje and me have been collaborating and have some working code! I'll open a PR, but wanted to get your input on what kind of method to add. Something like `Wallet.ExportEncryptedKeyNep2()`, or a more generic Helper, what do you think @localhuman?
