### ISSUE TITLE
neo-python description on pypi.org is not displayed correctly

### ISSUE THREAD

**Issue by dauTT** [CityOfZion/neo-python#655]
### Current behavior

neo-python description on [pypi.org](https://pypi.org/project/neo-python/) is not displayed correctly: 

![image](https://user-images.githubusercontent.com/30392990/46636782-bd1b2200-cb59-11e8-96c3-d1f3d8c432c6.png)

### Expected behavior
It should display a nice description.

### Your environment

- OS: Ubuntu 
- neo-python version: `v0.8.2-dev`
- Python version: `3.6.5`

**Comment by ixje** [comment]
probable cause might be this
```
(venv) Eriks-Air:neo-python erik$ python setup.py check --restructuredtext
/Users/erik/Documents/code/test-issues/neo-python/venv/lib/python3.6/site-packages/setuptools/dist.py:397: UserWarning: Normalizing '0.8.2-dev' to '0.8.2.dev0'
  normalized_version,
running check
warning: Check: The project's long_description has invalid markup which will not be rendered on PyPI. The following syntax errors were detected:
line 186: Warning: Title underline too short.

Python 3.6+
~~~~~~~~~~
```

requires `pip install readme`

**Comment by dauTT** [comment]
Woh! now neo-python description on pypi.org looks really professional!! :+1:
