### ISSUE TITLE
Can I use fully synced blockchain for neo-python which was synced using neo-cli?

### ISSUE THREAD

**Issue by skinderis** [CityOfZion/neo-python#656]
I have fully synced blockchain in `BlockchainFolder` directory:
```
--BlockchainFolder
----Index
--------Contains some blockchain files
----Chain
--------Contains full NEO blockchain
```
Is there anyway to add this synced blockchain to the folder that neo-python uses? There is file structure:
```
--~/.neopython/Chains
----SC234
----Test_Notif
```

So, if it's possible to use synced blockchain for neo-python, where should I move `Chain` folder and `Index` folder?

Thank you!

**Comment by skinderis** [comment]
I tried to move all files from `Chain` folder and I get this error:
![image](https://user-images.githubusercontent.com/24273695/46683160-294c6300-cbf8-11e8-8e1c-80faa76b11fd.png)

**Comment by ixje** [comment]
`neo-cli` and `neo-python` chain files are not compatible. Your best option is to use the `np-bootstrap` command, which will download a `neo-python` compatible chain that's close to fully synced. Often it's around 95% and you only have to do the last bit.
