### ISSUE TITLE
wallet create_addr is showing error message 

### ISSUE THREAD

**Issue by wanglongfei88** [CityOfZion/neo-python#670]
### Current behavior
I am currently using neo-python to create an address after opened a wallet. And it shows an error message as 
```
neo> wallet create_addr 1
[I 181018 09:01:44 UserWallet:154] contract does not exist yet
```
Actually, the address is created success. 
![wallet create address](https://user-images.githubusercontent.com/34025001/47143597-1fadb400-d2f8-11e8-81cb-b68a7ec369c7.png)

### Expected behavior

- display a success message

### How to reproduce

- Access the privatenet using ```np-prompt -p```
- open your wallet ```open wallet ***.json```
- run ```wallet``` (remember how many address)
- run ```wallet create_addr 1```
- run ```wallet``` (compare address with previous result)

### Your environment

Let us know in what environment you're running into the issue:

- OS: (Windows version) 
- neo-python version: `neo-python v0.8.1`
- Python version: `3.7.0`

**Comment by jseagrave21** [comment]
@wanglongfei88 this message is expected as shown here https://github.com/CityOfZion/neo-python/blob/1790581bfb9c91e92814fe6624997f90c08f989f/neo/Implementations/Wallets/peewee/UserWallet.py#L154 because the script is checking to see if the address created already exists in the database.

**Comment by jseagrave21** [comment]
You make a good point though. Thank you for the feedback! We can definitely do that.
