### ISSUE TITLE
Disconnected peers are not cleaned up properly

### ISSUE THREAD

**Issue by ThomasLobker** [CityOfZion/neo-python#687]
### Current behavior
When a connected peer disconnects, it should clean up the connection, the scheduled tasks and the used variables. Currently the tasks keep running. This means that if a peer disconnects a lot, then the background tasks keep building up and `neo-python` will start eating memory.

### Expected behavior
Disconnected peers should be cleaned up and all looping and deferred tasks should be cancelled and stopped.

### How to reproduce
Start a node with only `maxpeers=1` and remotely disconnect that peer for a second. Once the peer is reconnected the logging will show two connected peers collecting blocks.

```
[D 181028 07:30:29 NeoNode:628] [5][mode 2] IPv4Address(type='TCP', host='127.0.0.1', port=30333) - asked for more blocks ... 2486841 thru 2486941 (100 blocks) stale count 1 MBR: 358130 BCRLen: 8287 
[D 181028 07:30:30 NeoNode:628] [0][mode 2] IPv4Address(type='TCP', host='127.0.0.1', port=30333) - asked for more blocks ... 2497748 thru 2497848 (100 blocks) stale count 1 MBR: 376400 BCRLen: 8387 
[D 181028 07:30:30 NeoNode:628] [2][mode 2] IPv4Address(type='TCP', host='127.0.0.1', port=30333) - asked for more blocks ... 2491108 thru 2491208 (100 blocks) stale count 1 MBR: 366733 BCRLen: 8465 
[D 181028 07:30:30 NeoNode:628] [12][mode 2] IPv4Address(type='TCP', host='127.0.0.1', port=30333) - asked for more blocks ... 2480545 thru 2480645 (100 blocks) stale count 1 MBR: 347300 BCRLen: 8565 
[D 181028 07:30:30 NeoNode:628] [4][mode 2] IPv4Address(type='TCP', host='127.0.0.1', port=30333) - asked for more blocks ... 2488924 thru 2489024 (100 blocks) stale count 1 MBR: 362578 BCRLen: 8665 
[D 181028 07:30:31 NeoNode:628] [3][mode 2] IPv4Address(type='TCP', host='127.0.0.1', port=30333) - asked for more blocks ... 2489724 thru 2489824 (100 blocks) stale count 1 MBR: 364499 BCRLen: 8765 
[D 181028 07:30:31 NeoNode:628] [7][mode 2] IPv4Address(type='TCP', host='127.0.0.1', port=30333) - asked for more blocks ... 2484213 thru 2484313 (100 blocks) stale count 1 MBR: 354607 BCRLen: 8865 
[D 181028 07:30:31 NeoNode:628] [11][mode 2] IPv4Address(type='TCP', host='127.0.0.1', port=30333) - asked for more blocks ... 2480645 thru 2480745 (100 blocks) stale count 1 MBR: 347600 BCRLen: 8965 
[D 181028 07:30:31 NeoNode:628] [8][mode 2] IPv4Address(type='TCP', host='127.0.0.1', port=30333) - asked for more blocks ... 2481609 thru 2481709 (100 blocks) stale count 1 MBR: 350700 BCRLen: 9065 
```

### Your environment
- OS: Ubuntu 18.04 in Docker
- neo-python version: 0.8.1
- Python version: 3.6

**Comment by jseagrave21** [comment]
Hey this is a great fix! I have been noticing the trend for toward max memory consumption while running my API server. I thought it was normal. Normally when I start the server I am at about 3/8 Gb. After a day or so, I will usually be sitting at 7+/8 Gb in use. Was this the cause?

**Comment by ThomasLobker** [comment]
@jseagrave21 the impact is the mostly during initial sync, when new blocks are coming in faster. But overall you should notice some improvements in a fully synced node as well. I'm curious if memory usage improves for you, so please let me know.

**Comment by jseagrave21** [comment]
@ThomasLobker After running for awhile now with a fresh dev pull, I noticed that the initial startup took much longer but once it started, the server has been running quite smoothly. Memory has remained at 3/8 Gb in use.

**Comment by jseagrave21** [comment]
Well, my server is still running well but RAM in use has continued to creep up like before. I am not sure if this is bad or good. My server has been running for almost 20 hrs and RAM in use by Python is now 4.5/8 Gb. Otherwise, it seems to be running smoothly.
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "Progress": [
            2912996,
            "/",
            2912996
        ],
        "Block-cache length": 0,
        "Blocks since program start": 3202,
        "Time elapsed (minutes)": 1193.6158990333333,
        "Blocks per min": 2.6826050177391108,
        "TPS": 1.0109198453013424
    }
}
```
