### ISSUE TITLE
Notifications by contract for global assets

### ISSUE THREAD

**Issue by financeforgeek** [CityOfZion/neo-python#694]
Current behavior

There is currently a method to get the addresses by contract for NEP-5 (/notifications/contract/script_hash) but there is no way that I know of to get the same thing for global assets. After talking to @jseagrave21 on discord it seems from RPC (ExtendedJsonRpcApi.) it could be added as a new method.  

Expected behavior

/notifications/contract/script_hash should return the same thing for both NEP-5 and for global assets (currently empty return for global assets).

**Comment by jseagrave21** [comment]
I am working on this but just wanted to clarify. My intention is to create an RPC method for ExtendedJsonRpcApi that will work for NEO/GAS while the REST method, "notifications by contract", would continue to be used for NEP5 tokens.

**Comment by ixje** [comment]
The discussion seems to be inactive. Closing for now. If you want to continue let me know and I can re-open

**Comment by jseagrave21** [comment]
@ixje Once "extended" methods are transferred to plugins. Perhaps these methods can live on as "plugins" in my neo-python fork?

**Comment by ixje** [comment]
absolutely. I can add your repo to the readme for others to find plugins at
