### ISSUE TITLE
getting error while running  np-bootstrap

### ISSUE THREAD

**Issue by AnkitRathore175** [CityOfZion/neo-python#700]
### Current behavior
- Are you using the latest available version? If not, first update and verify the problem still exists.
- What is the problem?
when running  np-bootstrap for testnet, it's download bootstrap chain successfully, but after that occured an error says "RuntimeError: cannot join current thread"
- Include a screenshot if it makes sense.
![image](https://user-images.githubusercontent.com/38749604/47900661-aa1f1780-dea3-11e8-8d39-6710d1b1ddfd.png)

### Expected behavior

- What should be happening?
it should not create error as i suppose
- Include a screenshot if it makes sense.

### How to reproduce

- Please explain the steps to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of this project.
just followed steps to configure neo-python and got this issue

### Your environment

Let us know in what environment you're running into the issue:

- OS: (Windows version/Linux distro/OSX version) 
ubuntu 16.04 64-bit
- neo-python version: (hint: use `np-prompt --version`)
neo-python v0.8.2
- Python version: (hint: `python -V`)
Python 3.6.7

**Comment by ixje** [comment]
This is a problem with the `tqdm` package. Their Github has issue reports and it's up to them to fix it. For now you can try to downgrade the package: `pip install tqdm==4.23.4`

**Comment by ixje** [comment]
ah you're using `np-bootstrap`. Try
```
pip install tqdm==4.23.4
python neo/bin/bootstrap.py
```

`np-bootstrap` is a shortcut to `neo/bin/bootstrap.py` but does additional requirements checking. You can circumvent that using the above direct access method.

The `path` for `create wallet` is the destination path where you want to store it relative to the neo-python folder e.g.
```
neo> create wallet Wallets/mywallet
[password]> **********
[password again]> **********
```
creates a wallet under `/neo-python-installation-dir/Wallets/mywallet`
