### ISSUE TITLE
wrong instructions on dockerhub

### ISSUE THREAD

**Issue by Pega88** [CityOfZion/neo-python#702]
### Current behavior
On the [dockerhub](https://hub.docker.com/r/cityofzion/neo-python/) instructions for neo-python, on the section "Running the image standalone", it says to execute `docker pull cityofzion/neo-privatenet`. 

This will pull the container image from [this github](https://github.com/CityOfZion/neo-privatenet-docker), which is [this dockerhub](https://hub.docker.com/r/cityofzion/neo-privatenet/), with a full private net, instead of the correct one, which should be `docker pull cityofzion/neo-python`.

**Comment by ixje** [comment]
thanks, fixed!
