### ISSUE TITLE
estack.Pop().GetBigInteger() -> AttributeError: 'NoneType' object has no attribute 'GetBigInteger'

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neo-python#71]
Was watching TestNet and keep seeing this exception over and over: 

    Traceback (most recent call last):
    File "/opt/neo/neo-python/neo/VM/ExecutionEngine.py", line 789, in StepInto
        self.ExecuteOp(op, self.CurrentContext)
    File "/opt/neo/neo-python/neo/VM/ExecutionEngine.py", line 432, in ExecuteOp
        x2 = estack.Pop().GetBigInteger()
    AttributeError: 'NoneType' object has no attribute 'GetBigInteger'

Here with more context:

    [Neo.Storage.Get] [Script:50cff8131c66e0ecfb92153b78a9faf512906fe7] [b'mult'] -> bytearray(b'01101201E01201311202F01401511412611502712612912811312802A12901C12B01012B01C01D01H01D01H01E02G02F01H02G')
        ERROR - neo.VM.ExecutionEngine.ExecutionEngine(L:792) - Exception
    Traceback (most recent call last):
    File "/opt/neo/neo-python/neo/VM/ExecutionEngine.py", line 789, in StepInto
        self.ExecuteOp(op, self.CurrentContext)
    File "/opt/neo/neo-python/neo/VM/ExecutionEngine.py", line 432, in ExecuteOp
        x2 = estack.Pop().GetBigInteger()
    AttributeError: 'NoneType' object has no attribute 'GetBigInteger'
    [neo.Implementations.Blockchains.LevelDBBlockchain.PersistBlock: engine execute result] Could not execute smart contract.  See logs for more details. 'NoneType' object has no attribute 'GetBigInteger'
    [neo.Implementations.Blockchains.LevelDBBlockchain.PersistBlock: Invoke tx] -> index, tx hash 735542 b'8b30bdab9c25b0f0e3ef91639a34e1e58b0df3b3f74ef0359dc253ec59bec16e'
    [Neo.Storage.Get] [Script:50cff8131c66e0ecfb92153b78a9faf512906fe7] [b'mult'] -> bytearray(b'01101201E01201311202F01401511412611502712612912811312802A12901C12B01012B01C01D01H01D01H01E02G02F01H02G')
        ERROR - neo.VM.ExecutionEngine.ExecutionEngine(L:792) - Exception
    Traceback (most recent call last):
    File "/opt/neo/neo-python/neo/VM/ExecutionEngine.py", line 789, in StepInto
        self.ExecuteOp(op, self.CurrentContext)
    File "/opt/neo/neo-python/neo/VM/ExecutionEngine.py", line 432, in ExecuteOp
        x2 = estack.Pop().GetBigInteger()
    AttributeError: 'NoneType' object has no attribute 'GetBigInteger'
    [neo.Implementations.Blockchains.LevelDBBlockchain.PersistBlock: engine execute result] Could not execute smart contract.  See logs for more details. 'NoneType' object has no attribute 'GetBigInteger'
    [neo.Implementations.Blockchains.LevelDBBlockchain.PersistBlock: Invoke tx] -> index, tx hash 735543 b'162c9fb702d7d6dcb5fe01578a765e27c5a8db4a0f48b83b58d75d7eb3b865ea'
    [neo.Implementations.Blockchains.LevelDBBlockchain.PersistBlock: engine execute] -> Success
    [neo.Implementations.Blockchains.LevelDBBlockchain.PersistBlock: engine execute result] -> IOp Interface: <neo.Core.State.ContractState.ContractState object at 0x7f9fa6a9e5c0>
    [neo.Implementations.Blockchains.LevelDBBlockchain.PersistBlock: Invoke tx] -> index, tx hash 735549 b'65d6e4360465d62f36e953afb0a839aa5f31c4e99e5b1f7d2c73ee186869822a'
    [Neo.Storage.Get] [Script:50cff8131c66e0ecfb92153b78a9faf512906fe7] [b'm'] -> 0
    [Neo.Storage.Put] [Script: 50cff8131c66e0ecfb92153b78a9faf512906fe7] [b'm'] -> bytearray(b'01101201E01201311202F01401511412611502712612912811312802A12901C12B01012B01C01D01H01D01H01E02G02F01H02G')
    [neo.SmartContract.StateReader] -> RUNTIME.Log: b'D-'
    [neo.Implementations.Blockchains.LevelDBBlockchain.PersistBlock: engine execute] -> Success
    [neo.Implementations.Blockchains.LevelDBBlockchain.PersistBlock: engine execute result] -> Array: []
    [neo.Implementations.Blockchains.LevelDBBlockchain.PersistBlock: engine execute result] -> ByteArray: bytearray(b'\x00')
        [neo.Implementations.Blockchains.LevelDBBlockchain.PersistBlock: Invoke tx] -> index, tx hash 735553 b'c7ee7dafd07b13879cd264c408207427708a0ec01897be596caf614151c594da'
    [Neo.Storage.Get] [Script:50cff8131c66e0ecfb92153b78a9faf512906fe7] [b'm'] -> bytearray(b'01101201E01201311202F01401511412611502712612912811312802A12901C12B01012B01C01D01H01D01H01E02G02F01H02G')
        ERROR - neo.VM.ExecutionEngine.ExecutionEngine(L:792) - Exception
    Traceback (most recent call last):
    File "/opt/neo/neo-python/neo/VM/ExecutionEngine.py", line 789, in StepInto
        self.ExecuteOp(op, self.CurrentContext)
    File "/opt/neo/neo-python/neo/VM/ExecutionEngine.py", line 432, in ExecuteOp
        x2 = estack.Pop().GetBigInteger()
    AttributeError: 'NoneType' object has no attribute 'GetBigInteger'

**Comment by localhuman** [comment]
I'll take a look at this.   There's a small chance there's an issue with the python vm, but my guess would be a faulty SC invocation.  Either way, the exception should be caught in a cleaner way-

**Comment by localhuman** [comment]
Are we still seeing this issue?

**Comment by metachris** [comment]
Not in quite a while. Closing it, we can reopen if it comes up again.
