### ISSUE TITLE
np-api-server after some time won't sync (it gets stuck)

### ISSUE THREAD

**Issue by skinderis** [CityOfZion/neo-python#711]
### Current behavior
- Are you using the latest available version? If not, first update and verify the problem still exists.
Yes.
- What is the problem?
Blockchain syncing gets stuck
- Include a screenshot if it makes sense.

[I 181107 21:17:22 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:17:37 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:17:52 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:18:07 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:18:22 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:18:37 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:18:52 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:19:07 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:19:22 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:19:37 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:19:52 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:20:07 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:20:22 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:20:37 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:20:52 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:21:07 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:21:22 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:21:37 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:21:52 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:22:07 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:22:22 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:22:37 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:22:52 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:23:07 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:23:22 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:23:37 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:23:52 threading:864] [MainNet] Block 2891714 / 2935358
[I 181107 21:24:07 threading:864] [MainNet] Block 2891714 / 2935358

### Expected behavior

- What should be happening?
It should continue syncing and get off from 2 891 714 block
- Include a screenshot if it makes sense.

### How to reproduce

- Please explain the steps to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of this project.
I just run a node on neo-python and run np-api-server --mainnet. When I run it, the blockchains is syncing for some time, but it gets stuck and won't continue, unless I restart docker container.

**Comment by dethos** [comment]
@skinderis this issue is already being discussed on https://github.com/CityOfZion/neo-python/issues/492

I think we should close this issue and continue the conversation there.

**Comment by ixje** [comment]
please discuss in the issue provided by dethos. We're aware of it and I'm testing some improvements as we speak. Can hopefully get them out in the coming days if they've proven successful.
