### ISSUE TITLE
Has anyone successfully called the example1 method in the build_raw_transactions file?

### ISSUE THREAD

**Issue by senhanxiao** [CityOfZion/neo-python#743]
Why raw_tx deserializes and finds scripts=[]?

**Comment by ixje** [comment]
Have at look at the file in the development branch. There have been some small updates including steps how to validate the correct working; https://github.com/CityOfZion/neo-python/blob/development/examples/build_raw_transactions.py

Second, if you want help then at least take the time to follow the guidelines and provide the necessary information such that we can help.

**Comment by senhanxiao** [comment]
{'txid': '0xff41c1b0f4b14942fcb1e2119fd3a82fbb36beb28b1d4dc05a744e16b5c39837', 'size': 242, 'type': 'ContractTransaction', 'version': 0, 'attributes': [{'usage': 144, 'data': '4d792072617720636f6e7472616374207472616e73616374696f6e206465736372697074696f6e'}, {'usage': 144, 'data': '4d792072617720636f6e7472616374207472616e73616374696f6e206465736372697074696f6e'}], 'vout': [{'n': 0, 'asset': '0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b', 'value': '1000', 'address': 'Ad9A1xPbuA5YBFr1XPznDwBwQzdckAjCev'}, {'n': 1, 'asset': '0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b', 'value': '99994000', 'address': 'AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y'}], 'vin': [{'txid': '0x30a4a3d282f2f7fa6119bdc080214a83ea8a018987da08947a184772f98dcab9', 'vout': 1}], 'sys_fee': '0', 'net_fee': '0', 'scripts': []}

scripts    aways  []
