### ISSUE TITLE
Get Contract State returns incorrect data model

### ISSUE THREAD

**Issue by saltyskip** [CityOfZion/neo-python#746]
### Current behavior
Calling RPC command get contractstate on a neo python node currently does not return the same data as neo-cli.

Using this RPC command
```
{
	"jsonrpc":"2.0",
	"method":"getcontractstate",
	"params":["33ee36c712b37df8acfbda4a1beb165e100ed3e0"],
	"id":1
}
```
will recieve this output
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "version": 0,
    "code": {
      "hash": "0x33ee36c712b37df8acfbda4a1beb165e100ed3e0",
      "script": "SCRIPT_OMITTED",
      "parameters": "0710",
      "returntype": 7
    },
    "name": "Stroage",
    "code_version": "1",
    "author": "THEKEY",
    "email": "yuandeng@hollycrm.com",
    "description": "THEKEY",
    "properties": {
      "storage": true,
      "dynamic_invoke": false,
      "payable": false
    }
  }
}
```

### Expected Behavior
The desired result should be the same one as NEO CLI node
```
"result": {
    "version": 0,
    "hash": "0x33ee36c712b37df8acfbda4a1beb165e100ed3e0",
    "script": "SCRIPT_OMITTED",
    "parameters": [
      "String",
      "Array"
    ],
    "returntype": "String",
    "name": "Stroage",
    "code_version": "1",
    "author": "THEKEY",
    "email": "yuandeng@hollycrm.com",
    "description": "THEKEY",
    "properties": {
      "storage": true,
      "dynamic_invoke": false
    }
  }
}
```

### How to reproduce
Execute the RPC command in any client like insomnia by targeting a neo python node like
http://node2.nyc3.bridgeprotocol.io:10332

### Your environment
No relevant

**Comment by ixje** [comment]
Thanks for the report!

So to summarise;
- there is no `result.code` object anymore
- `result.parameters` is now a list of argument type name strings
- `result.returntype` is now a argument type name string
- `result.properties` object does not have a `payable` key. (I actually think we should keep this, as I'm sure that will get added to neo-cli sooner or later) 

@jseagrave21

**Comment by jseagrave21** [comment]
@ixje I am working on this now.

**Comment by ixje** [comment]
@saltyskip fixed in dev branch thanks to @jseagrave21 👍
