### ISSUE TITLE
Support --change-addr and --to-addr for claim command

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo-python#755]
### Current behavior
The `claim` command does not support specifying to which address the claim is send, nor to which address potential change is send. 

### Expected behavior
We are refactoring the CLI commands according to this issue (#623) in the `refactor-prompt` branch. Once that issue is resolved we should enhance the `claim` command to support the above 2 parameters.

**Comment by jseagrave21** [comment]
@ixje does it make sense to have both a `--change-addr` and a `--to-addr`? I think the `--change-addr` introduced in `neo-cli` makes sense if you make partial GAS claims; however, we decided not to support making partial gas claims awhile back. The default address used by `ClaimGas` is the default change  address as seen here:
https://github.com/CityOfZion/neo-python/blob/4c1e0dc4068cf84e3f80698600b6ca86b8b5a1a3/neo/Prompt/Commands/Wallet.py#L310

I could add a single parameter for a `--to-addr` which would take precedence over the two inputs for `scripthash` seen here:
https://github.com/CityOfZion/neo-python/blob/4c1e0dc4068cf84e3f80698600b6ca86b8b5a1a3/neo/Prompt/Commands/Wallet.py#L310-L318
if it was present.
What do you think?

**Comment by ixje** [comment]
The partial GAS claim referred to having e.g. "100 unclaimed gas" and only wanting to get e.g. only 50 of that released. This would allow you to release all 100, but send 90 to address_x and 10 back to yourself.

With all the UTXO mess it might be smart to simplify it until there's a real hard request for it. So just having a `--to-addr` for the time being sounds like the right thing.

**Comment by jseagrave21** [comment]
Okay, I would like to work on this.

**Comment by jseagrave21** [comment]
@ixje I am ready to PR the `--to-addr` addition. Per your guidance above, I will wait until #623 is merged.

**Comment by jseagrave21** [comment]
After reading https://github.com/neo-project/neo-cli/pull/270#issue-237609402 and looking at the code again, I think what they are calling the "change address" is actually what we are calling the --to-addr. What do you think, @ixje?
