### ISSUE TITLE
[Feature] Configurable logging

### ISSUE THREAD

**Issue by localhuman** [CityOfZion/neo-python#76]
Right now there's 2 logs- print to the console ( fun, but annoying sometimes ) and log to `prompt.log`.

Ideally we'd keep `prompt.log` as it is, but add another log or loglevel to print smart contract debugging statements and `Runtime.Notify` events.

**Comment by metachris** [comment]
Good idea. What kind of events would that include?

* `Neo.Runtime.*`
* `Neo.Storage.*`
* `neo.SmartContract.*`

Are those it? Any else?

Perhaps would be a good moment to think about a more generic, versatile logging setup. Perhaps a central logger where other components can subscribe for events. One of these components could be the contract filelogger, which subscribes to the above events.

**Comment by metachris** [comment]
I think using something like [pymitter](https://github.com/riga/pymitter#examples) would be a good fit for this. It's like an event queue and pubsub system. Any part in the code can submit events (eg. `Neo.Storage.PUT`), and anyone can subscribe to messages:

```
from pymitter import EventEmitter

ee = EventEmitter(wildcards=True)

@ee.on("myevent.foo")
def handler1():
    print "handler1 called"

@ee.on("myevent.bar")
def handler2():
    print "handler2 called"

@ee.on("myevent.*")
def hander3():
    print "handler3 called"


ee.emit("myevent.foo")
# -> "handler1 called"
# -> "handler3 called"

ee.emit("myevent.bar")
# -> "handler2 called"
# -> "handler3 called"

ee.emit("myevent.*")
# -> "handler1 called"
# -> "handler2 called"
# -> "handler3 called"
```

I've had very good experiences with it. I built a [RFID driven music player](https://github.com/metachris/rfid-music-player/tree/master/src-python) for my daughter, where various components communicate with each other this way: 

![image](https://raw.githubusercontent.com/metachris/rfid-music-player/master/docs/python-architecture-overview.jpg)

In neo-python, the EventHub would kind of sit on the outside, compared to center stage at the music player.

(PS: I think a schematic like this would be great to have for neo-python.)

**Comment by metachris** [comment]
Done with #90 and #91
