### ISSUE TITLE
Error creating list from attached gas value

### ISSUE THREAD

**Issue by mmoravec** [CityOfZion/neo-python#77]
# Issue
When compiling and importing a contract resembling a NEP5 token scenario, I try to create a list with a length assigned to the amount of gas attached

# Contract 

```
from boa.blockchain.vm.Neo.Storage import Get, Put, Delete, GetContext
from boa.blockchain.vm.Neo.Runtime import Notify
from boa.blockchain.vm.System.ExecutionEngine import GetScriptContainer, GetExecutingScriptHash
from boa.blockchain.vm.Neo.Blockchain import GetHeight, GetHeader
from boa.blockchain.vm.Neo.Runtime import GetTrigger, CheckWitness
from boa.blockchain.vm.Neo.Output import GetScriptHash, GetValue, GetAssetId
from boa.code.builtins import concat, list, range, take, substr

SERIALIZED_NAME = 'AWESOME'

GAS_ASSET_ID = b'\xe7-(iy\xeel\xb1\xb7\xe6]\xfd\xdf\xb2\xe3\x84\x10\x0b\x8d\x14\x8ewX\xdeB\xe4\x16\x8bqy,`'
OWNER = b'\xda\x06\xe3G\xda\x9c(\x9eWv-6\x0c\xac9~\x90\x92\x88\xf7'
TWOWEEKS = 1209600000

def Main(operation):
    tx = GetScriptContainer()
    context = GetContext()
    references = tx.References

    print("adding entry")
    if len(references) < 1:
        print("no gas attached")
        return False

    print("reading reference")
    reference = references[0]
    print("reference read")

    sender = GetScriptHash(reference)
    print("sender hash is")
    print(sender)
    print("reading script hash")
    print("getting asset ID. ID is here:")
    output_asset_id = GetAssetId(reference)
    print(output_asset_id)
    print('asset id printed above')
    if output_asset_id == GAS_ASSET_ID:
        print("executing script hash")
        receiver = GetExecutingScriptHash()
        for output in tx.Outputs:
            shash = GetScriptHash(output)
            print("getting shash..")
            if shash == receiver:
                print("adding value?")
                value = GetValue(output)
                print("value storing in entries")
                Notify(value)
                print('string we will save to the entries array')
                entries = Get(context, 'entries')
                print('current entries')
                print(entries)
                new_entries = list(length=value)
                Notify(new_entries)

    return entries
```
# Result when compiled
<img width="1077" alt="screen shot 2017-11-08 at 11 12 48 pm" src="https://user-images.githubusercontent.com/2295826/32592968-dbe8a080-c4da-11e7-9f7a-6fb60edced8a.png">

The compilation fails. When I assign a static number of 10 to `new_entries = list(length=value)` to the list and Notify the value of GetValue(output) I get the following:

<img width="1077" alt="screen shot 2017-11-08 at 11 14 24 pm" src="https://user-images.githubusercontent.com/2295826/32592932-b933187c-c4da-11e7-954e-49a5efb5e243.png">

I'm not sure how to resolve this compiler issue. You can see that even though I attached 3 gas the Notify call says that I attached 300000000.

**Comment by mmoravec** [comment]
I've also attempted to create a list of length 3000 and the compiler errors out. I'm able to create a list of length 300.

**Comment by mmoravec** [comment]
I've also found that the VM multiplies every gas attached by 100 million, so if i attach 2 gas it becomes 200 million.

**Comment by ixje** [comment]
That multiplication by 100 million is to convert it to the format required by the network protocol.

**Comment by localhuman** [comment]
The max list length is enforced by [the VM ](https://github.com/neo-project/neo/blob/master/neo/SmartContract/ApplicationEngine.cs#L29)

I believe the issue is trying to create a list of length 0, which is currently not supported.  List lengths are not mutable in the VM, so a list of length 0 would not be very much use!

A work around would be to check if  `entries` is greater than 0, and only create a new list in that case.

**Comment by mmoravec** [comment]
@localhuman could be interesting to eventually allow mutable lists in neo-python and just work around how it would be done with the VM. For now we'll work around these limitations. Thanks for the information 👍
