### ISSUE TITLE
Idea: add pyup.io

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neo-python#84]
pyup.io is a service that helps you to keep your requirements files up to date. It sends you automated pull requests whenever there’s a new release for one of your dependencies.

https://pyup.io

**Comment by ixje** [comment]
@metachris ping :)

**Comment by LysanderGG** [comment]
I checked out pyup.io (see #819)
@ixje do you have the necessary credentials to set-it up now?

**Comment by LysanderGG** [comment]
Note: we got a lot of merge requests to `master` because it is the current default branch.
Imo the default branch should be changed to `development` (merge requests will also default to merges to `development`).

**Comment by ixje** [comment]
Closing due to focus on NEO3
