### ISSUE TITLE
unresolved external symbol "public: void __cdecl leveldb::WriteBatch::Clear(void)"

### ISSUE THREAD

**Issue by Qiao-Jin** [CityOfZion/neo-python#867]
I am trying to install neo-python on WIN10 system according to [Installation (Windows)]https://neo-python.readthedocs.io/en/latest/installwindows.html#troubleshooting).

Every step is strictly same as this introduction. But when I was building plyvel with:

python setup.py build_ext --inplace --force

I ran into the following errors. This is weird cuz I have copied leveldb header files to

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include

and leveldb.lib to 

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\lib\x64
and
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\lib\x86

Could someone give me a hint? Thx so much!

_plyvel.obj : error LNK2001: unresolved external symbol "public: void __cdecl leveldb::WriteBatch::Clear(void)" (?Clear@WriteBatch@leveldb@@QEAAXXZ)
_plyvel.obj : error LNK2001: unresolved external symbol "public: void __cdecl leveldb::WriteBatch::Delete(class leveldb::Slice const &)" (?Delete@WriteBatch@leveldb@@QEAAXAEBVSlice@2@@Z)
_plyvel.obj : error LNK2001: unresolved external symbol "public: void __cdecl leveldb::WriteBatch::Put(class leveldb::Slice const &,class leveldb::Slice const &)" (?Put@WriteBatch@leveldb@@QEAAXAEBVSlice@2@0@Z)
_plyvel.obj : error LNK2001: unresolved external symbol "public: __cdecl leveldb::WriteBatch::~WriteBatch(void)" (??1WriteBatch@leveldb@@QEAA@XZ)
_plyvel.obj : error LNK2001: unresolved external symbol "public: __cdecl leveldb::WriteBatch::WriteBatch(void)" (??0WriteBatch@leveldb@@QEAA@XZ)
_plyvel.obj : error LNK2001: unresolved external symbol "class leveldb::FilterPolicy const * __cdecl leveldb::NewBloomFilterPolicy(int)" (?NewBloomFilterPolicy@leveldb@@YAPEBVFilterPolicy@1@H@Z)
_plyvel.obj : error LNK2001: unresolved external symbol "class leveldb::Status __cdecl leveldb::RepairDB(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,struct leveldb::Options const &)" (?RepairDB@leveldb@@YA?AVStatus@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBUOptions@1@@Z)
_plyvel.obj : error LNK2001: unresolved external symbol "class leveldb::Status __cdecl leveldb::DestroyDB(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,struct leveldb::Options const &)" (?DestroyDB@leveldb@@YA?AVStatus@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBUOptions@1@@Z)
_plyvel.obj : error LNK2001: unresolved external symbol "public: static class leveldb::Status __cdecl leveldb::DB::Open(struct leveldb::Options const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class leveldb::DB * *)" (?Open@DB@leveldb@@SA?AVStatus@2@AEBUOptions@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAPEAV12@@Z)
_plyvel.obj : error LNK2001: unresolved external symbol "class leveldb::Cache * __cdecl leveldb::NewLRUCache(unsigned __int64)" (?NewLRUCache@leveldb@@YAPEAVCache@1@_K@Z)
_plyvel.obj : error LNK2001: unresolved external symbol "class leveldb::Comparator const * __cdecl leveldb::BytewiseComparator(void)" (?BytewiseComparator@leveldb@@YAPEBVComparator@1@XZ)
_plyvel.obj : error LNK2001: unresolved external symbol "public: __cdecl leveldb::Options::Options(void)" (??0Options@leveldb@@QEAA@XZ)
_plyvel.obj : error LNK2001: unresolved external symbol "private: static char const * __cdecl leveldb::Status::CopyState(char const *)" (?CopyState@Status@leveldb@@CAPEBDPEBD@Z)
_plyvel.obj : error LNK2001: unresolved external symbol "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl leveldb::Status::ToString(void)const " (?ToString@Status@leveldb@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)

**Comment by Qiao-Jin** [comment]
Solved after reopening PC.

**Comment by jseagrave21** [comment]
If this issue is resolved could you close it?
