### ISSUE TITLE
Is there doc on how to start a private chain by neo-python?

### ISSUE THREAD

**Issue by Qiao-Jin** [CityOfZion/neo-python#870]
I am currently trying to start a private chain by NEO-python. But there seems no document on building up private chain on NEO-python.
Besides, is there detailed info on the definition of items in protocol config file?  Thx

**Comment by jseagrave21** [comment]
You can follow the readme here https://github.com/CityOfZion/neo-privatenet-docker
Or checkout this article https://medium.com/proof-of-working/how-to-run-a-private-network-of-the-neo-blockchain-d83004557359

**Comment by Qiao-Jin** [comment]
Thanks very much!
