### ISSUE TITLE
I pulled the Docker image and used it, but I can not synchronize the wallet.

### ISSUE THREAD

**Issue by okayu8** [CityOfZion/neo-python#879]
Hello. Please do not hesitate to contact me because my private network connection is not good.

I docker pull  Ver: 0.8.3 image and use it.
https://hub.docker.com/r/cityofzion/neo-privatenet?ref=login

After I run the image, I copy the local Smart contract to the container and erase the old block chain data.
```
docker cp localFilePath / compileSmartContract.avm neo-privatenet: /neo-python/filename.avm
rm -rf /root/.neopython/Chains/privnet*
```

Then start the interface with the `neopy` command.

When opening the wallet with the following command and checking the wallet with the wallet command, it seems that it is "percent_synced": 0 "and it is not possible to synchronize the wallet.
`open wallet neo-privnet.wallet`

Progress of PriveteNet is displayed as 1/1.
If you connect immediately after PC start up, you may be able to synchronize well in rare cases.

Do you know for why this phenomenon is caused? Thank you very much.

---
neo-python ver: 0.8.3
Docker Desktop ver: Version 2.0.0.0-win81 (29211)
OS: Windows10

**Comment by ixje** [comment]
The docker image you refer to is not `neo-python`, but a private blockchain docker image. I don't know why it includes `neo-python` in the image, but it is not `neo-python` version `0.8.3` but `0.8.2`.

> (venv) Eriks-Air:neo-python erik$ docker exec -it neo-privatenet /bin/bash
> 
> * Consensus nodes are running in screen sessions, check 'screen -ls'
> * neo-python is installed in /neo-python, with a neo-privnet.wallet file in place
> * You can use the alias 'neopy' in the shell to start neo-python's prompt.py with privnet settings
> * Please report issues to https://github.com/CityOfZion/neo-privatenet-docker
> 
> root@2ccf9742661a:/neo-python# cat /neo-python/neo/__init__.py
> __version__ = '0.8.2'

With the limited `neo-python` resources we have at th moment I cannot spent time on debugging `0.8.2` issues. My recommendation is to install `neo-python` `0.8.3` from git and connect that to your private network by running e.g. `np-prompt -p`. If you insist on using a docker image then pull `0.8.3` from here https://hub.docker.com/r/cityofzion/neo-python/

**Comment by okayu8** [comment]
@ixje 
Thank you for your kindness.
I'm sorry, apparently I seem to have made a mistake in the place.

Report it to the following URL.
* https://github.com/CityOfZion/neo-privatenet-docker

Thank you very much.

**Comment by ixje** [comment]
No problem. If the `0.8.3` version gives you problems, please report them and I'll try to help/resolve.
