### ISSUE TITLE
Update neo-python-rpc with latest RPC calls

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo-python#884]
The NEO RPC server is constantly being updated with new calls or output enhancements. The [nep-python-rpc](https://github.com/CityOfZion/neo-python-rpc) project should be updated to support the latest available calls. See the [documentation](https://docs.neo.org/en-us/node/cli/2.9.4/api.html) for available RPC calls.

**Comment by jseagrave21** [comment]
@ixje do you still want to exclude `dumpprivkey`?

**Comment by ixje** [comment]
> @ixje do you still want to exclude `dumpprivkey`?
Yes

**Comment by ixje** [comment]
Finished. Closing to avoid double work.
