### ISSUE TITLE
Update to throw exceptions instead of logging errors [np-main]

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo-python#891]
This is a TODO for a project (see side bar)

Try to remove as much logging errors inside the business logic and raise Exceptions instead. Try to bubble it up to the point the that presentation layer (at this point only a CLI) can present useful and detailed information (if necessary).
- Do not use the generic Exception class but use the more specific exception classes like `ValueError`, `TypeError` etc ([standard lib exceptions](https://docs.python.org/3/library/exceptions.html)).
- Create custom exceptions if needed to give sufficient control to the end-user.

**Comment by jseagrave21** [comment]
@ixje are you sure this one is done and not #888?
