### ISSUE TITLE
Remove undocumented “smart code” 

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo-python#893]
This is a TODO for a project (see side bar)

Remove undocumented “smart code” to reduce user confusion and to give the user the control they need.

[Example 1](https://github.com/CityOfZion/neo-python/blob/e561e5b57d4093a9ee0c87a8312d4a4d16f6fd5e/neo/SmartContract/StateMachine.py#L398-L404):  storing a bytearray of length 20 in a smart contract gets automatically convert to a NEO address.
[Example 2](https://github.com/CityOfZion/neo-python/blob/e561e5b57d4093a9ee0c87a8312d4a4d16f6fd5e/neo/Prompt/Utils.py#L255): entering a NEO address on the CLI as Smart Contract input automatically gets converted to a script hash.

This issue should be updated to collect more "smart code" when encountered.

**Comment by ThomasLobker** [comment]
I think in `np-prompt` it's quite convenient to have human readable strings for in- and output. But then all smart code should move from other parts of the code to np-prompt. How about a setting to enable or disable heuristic decoding in np-prompt? Throughout the rest of the code, where people use `neo-python` as an SDK, it should be consistent and in my opinion hexified binary strings.

```diff
--- a/neo/SmartContract/StateMachine.py
+++ b/neo/SmartContract/StateMachine.py
@@ -1,4 +1,5 @@
 import sys
+import binascii
 from neo.Core.State.ContractState import ContractState
 from neo.Core.State.AssetState import AssetState
 from neo.Core.Blockchain import Blockchain
@@ -392,16 +393,8 @@ def Storage_Put(self, engine: ExecutionEngine):
         storage_key = StorageKey(script_hash=context.ScriptHash, key=key)
         item = self._storages.ReplaceOrAdd(storage_key.ToArray(), new_item)
 
-        keystr = key
-        valStr = bytearray(item.Value)
-
-        if len(key) == 20:
-            keystr = Crypto.ToAddress(UInt160(data=key))
-
-            try:
-                valStr = int.from_bytes(valStr, 'little')
-            except Exception as e:
-                pass
+        keystr = binascii.hexlify(key).decode('ascii')
+        valStr = binascii.hexlify(bytearray(item.Value)).decode('ascii')
 
         self.events_to_dispatch.append(
             SmartContractEvent(SmartContractEvent.STORAGE_PUT, ContractParameter(ContractParameterType.String, '%s -> %s' % (keystr, valStr)),
@@ -422,9 +415,7 @@ def Storage_Delete(self, engine: ExecutionEngine):
 
         storage_key = StorageKey(script_hash=context.ScriptHash, key=key)
 
-        keystr = key
-        if len(key) == 20:
-            keystr = Crypto.ToAddress(UInt160(data=key))
+        keystr = binascii.hexlify(key).decode('ascii')
 
         self.events_to_dispatch.append(SmartContractEvent(SmartContractEvent.STORAGE_DELETE, ContractParameter(ContractParameterType.String, keystr),
                                                           context.ScriptHash, Blockchain.Default().Height + 1,
```

This change works for us to keep storage events undecoded.

**Comment by ixje** [comment]
some smart code has been removed. Currently considered sufficient for LTS of 2.0. We'll focus on NEO3.0 build and keep this in mind
