### ISSUE TITLE
Improve data(base) access

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo-python#894]
This is a roadmap milestone item.
See the `Roadmap` project on the side bar for more information where it fits in the bigger picture.
See the `improve data(base) access` project on the side bar for a breakdown of items and progress.

**Rationale**
The current used database (`leveldb`) only allows single process access. The idea behind this objective is to improve accessibility to processed data from other system/processes. This requires supporting a backend which at least allows reads from multiple processes simultaneously.

**Comment by merl111** [comment]
I just started working on this issue. Talked to @ixje on Discord.
Progress can be tracked through https://github.com/merl111/neo-python/tree/alt-db-support

The goal is to abstract the database access to support different database implementations.
