### ISSUE TITLE
Deployed with sc command but transaction does not exist

### ISSUE THREAD

**Issue by okayu8** [CityOfZion/neo-python#899]
I deployed the avm file with a new command, sc deploy.

sc deploy test.avm True False False 0710 05

Test deploy invoke successful is displayed,
When you enter the password at the end, tx is displayed.

However, after confirming the transaction with the show tx command, it is returning that tx is not found, it seems that it is not deployable.

Do you know why this is occurring?

neo-python ver : 0.8.4-dev
OS : MacOS Mojave

**Comment by ixje** [comment]
has this been solved by adding the `--fee=0.01` as I saw on #dev-general @ NEO Discord?

**Comment by okayu8** [comment]
@ixje 
thank you.
I did not know that fee is necessary for deploying over 1024 bytes.
I was able to deploy.

**Comment by ixje** [comment]
It is a recently introduced policy on the NEO blockchain so I can fully understand that you might not have known about it. Glad you were now able to deploy.
