### ISSUE TITLE
Unhandled error in Deferred pubnet

### ISSUE THREAD

**Issue by skinderis** [CityOfZion/neo-python#900]
Runing a node, I am getting the error:
```
[I 190219 13:32:14 threading:864] [MainNet] Block 46394 / 526000
[I 190219 13:32:29 threading:864] [MainNet] Block 47014 / 532000
[I 190219 13:32:44 threading:864] [MainNet] Block 47114 / 534000
[I 190219 13:32:59 threading:864] [MainNet] Block 47114 / 534000
[I 190219 13:33:22 _observer:131] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f4c6f78d9b0>
[I 190219 13:33:26 _observer:131] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f4c6f3e1e48>
[I 190219 13:33:26 _observer:131] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f4c6f3e1e48>
Unhandled error in Deferred:
[C 190219 13:33:28 _observer:131] Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/base.py", line 1152, in connectionFailed
    self.factory.clientConnectionFailed(self, reason)
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py", line 263, in clientConnectionFailed
    self._onConnection.errback(reason)
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 501, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/neo-python/neo/Network/NodeLeader.py", line 693, in clientConnectionFailed
    logger.debug(f"Failed connecting to {address} {ce.args[0].value}")
builtins.AttributeError: 'str' object has no attribute 'value'

[C 190219 13:33:28 _observer:131]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
        current.result = callback(current.result, *args, **kw)
      File "/root/neo-python/neo/Network/NodeLeader.py", line 693, in clientConnectionFailed
        logger.debug(f"Failed connecting to {address} {ce.args[0].value}")
    AttributeError: 'str' object has no attribute 'value'
[I 190219 13:33:29 threading:864] [MainNet] Block 47114 / 534000
[I 190219 13:33:44 threading:864] [MainNet] Block 47114 / 534000
[I 190219 13:34:00 threading:864] [MainNet] Block 47114 / 534000
[I 190219 13:34:15 threading:864] [MainNet] Block 47114 / 534000
[I 190219 13:34:30 threading:864] [MainNet] Block 47114 / 534000
[I 190219 13:34:45 threading:864] [MainNet] Block 47114 / 534000
[I 190219 13:35:00 threading:864] [MainNet] Block 47114 / 534000

```
After the error syncing stops. What might be the problem and how I can automatically continue syncing?

Thanks for the help!

**Comment by ixje** [comment]
You did not provide the information request by the template and so I cannot answer your question as I'm missing important information to do so. Please update and I can reopen

**Comment by skinderis** [comment]
Second error, causing syncing problems:

`[I 190220 14:34:20 threading:864] [MainNet] Block 1545426 / 3392107
[I 190220 14:34:25 LevelDBBlockchain:844] Could not persist block 1545443 reason: Invalid list operation
[D 190220 14:34:26 defer:654] On Persist blocks loop error! [Failure instance: Traceback: <class 'Exception'>: Invalid list operation
    /usr/lib/python3.6/threading.py:916:_bootstrap_inner
    /usr/lib/python3.6/threading.py:864:run
    /usr/local/lib/python3.6/dist-packages/twisted/_threads/_threadworker.py:46:work
    /usr/local/lib/python3.6/dist-packages/twisted/_threads/_team.py:190:doWork
    --- <exception caught here> ---
    /usr/local/lib/python3.6/dist-packages/twisted/python/threadpool.py:250:inContext
    /usr/local/lib/python3.6/dist-packages/twisted/python/threadpool.py:266:<lambda>
    /usr/local/lib/python3.6/dist-packages/twisted/python/context.py:122:callWithContext
    /usr/local/lib/python3.6/dist-packages/twisted/python/context.py:85:callWithContext
    /root/neo-python/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py:845:PersistBlocks
    /root/neo-python/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py:841:PersistBlocks
    /root/neo-python/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py:775:Persist
    /root/neo-python/neo/SmartContract/StateMachine.py:86:ExecutionCompleted
    /root/neo-python/neo/SmartContract/StateReader.py:307:ExecutionCompleted
    /root/neo-python/neo/VM/ExecutionEngine.py:79:CurrentContext
    /root/neo-python/neo/VM/RandomAccessStack.py:55:Peek
    ] 
[I 190220 14:34:35 threading:864] [MainNet] Block 1545443 / 3392113`
