### ISSUE TITLE
Transaction class instances retain old attributes

### ISSUE THREAD

**Issue by jseagrave21** [CityOfZion/neo-python#901]
### Current behavior
This issue was first [discovered](https://github.com/CityOfZion/neo-python/issues/886#issuecomment-467148923) by @lock9 and then further investigated by @jseagrave21 and @ixje.

Whenever an instance of a transaction is created the creator defines attributes in this manner:

```
def __init__(self, inputs=[], outputs=[], attributes=[], scripts=[]):
```
From @ixje "The problem with this is that you should not put mutable objects (e.g. a list) as the default values. because they are created only _once_ and then reused for all instances ever created."

This caused the issue discovered by @lock9. When creating new instances of `RawTransaction`, the previous attributes were retained and the new ones appended until the max (16) was reached.

### Expected behavior
A new transaction class should not retain old attributes. 

### How to reproduce
Create a new transaction and append an attribute in a loop. 

### Your environment

neo-python v0.8.4
Also references https://github.com/CityOfZion/neo-python/blob/9588aed21a58cf8f9e862679fd8a8cfa778fac5e/neo/Core/TX/RawTransaction.py

**Comment by lock9** [comment]
The fix provided by @ixje fixes the problem:

```python
def __init__(self, inputs=None, outputs=None, attributes=None, scripts=None):
        """
        Create an instance.
        Args:
            inputs (list): of neo.Core.CoinReference.CoinReference.
            outputs (list): of neo.Core.TX.Transaction.TransactionOutput items.
            attributes (list): of neo.Core.TX.TransactionAttribute.
            scripts:
        """
        super(Transaction, self).__init__()
        self.inputs = [] if inputs is None else inputs
        self.outputs = [] if outputs is None else outputs
        self.Attributes = [] if attributes is None else attributes
        self.scripts = [] if scripts is None else scripts
        self.InventoryType = 0x01  # InventoryType TX 0x01
        self.__references = None```

Thank you for the very quick fix!

**Comment by lock9** [comment]
Actually, it fixed the previous error, but now my transaction doesn't seem to be valid anymore.
http://chain.simpli.com.br:4000/transaction/6f998031dad23856580cb883801f9a2f3a22057ece8581c6fe1cb3a216fe7e68

And it supposed to be:
```scriptBuilder.EmitAppCallWithOperation(address_to_scripthash("Ad83tfsuWxxexhefPzXVpn5vv6oCbLKFEx"), "name") ```
