### ISSUE TITLE
When I perform my own operation, only the word "Error testing contract invoke" will return and fail.

### ISSUE THREAD

**Issue by okayu8** [CityOfZion/neo-python#904]
Hello.
I deployed Smart Contract on test net and confirmed the operation with neo-python.
The operation of NEP 5 can be executed as usual.
However, if you execute your own defined operation, only the word "Error testing contract invoke" will return and fail.
It worked normally when verifying operation with ver: 2.8.0 of neo-privatenet.
https://hub.docker.com/r/cityofzion/neo-privatenet?ref=login
Why does this occur?

**Comment by ixje** [comment]
Please following instructions of the issue template and provide the requested information. I cannot help you like this.

```
### Current behavior
- Are you using the latest available version? If not, first update and verify the problem still exists.
- What is the problem?
- Include a screenshot if it makes sense.

### Expected behavior

- What should be happening?
- Include a screenshot if it makes sense.

### How to reproduce

- Please explain the steps to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of this project.

### Your environment

Let us know in what environment you're running into the issue:

- OS: (Windows version/Linux distro/OSX version) 
- neo-python version: (hint: use `np-prompt --version`)
- Python version: (hint: `python -V`)
```

I will re-open once you've updated it to include the information required
