### ISSUE TITLE
Support for ABI

### ISSUE THREAD

**Issue by saltyskip** [CityOfZion/neo-python#908]
Is ABI support for contracts compiled with NEO python in the roadmap? As we get more complicated contracts out there, it becomes more necessary to be able to generate and look up the ABI's.

**Comment by ixje** [comment]
I didn't seem to receive a notification for this one, but better late then never.

Can you elaborate on what it would/should look like ? I have a feeling what your asking for is having the compiler spit out an ABI file for the .avm files it creates? If so, please post that on the https://github.com/CityOfZion/neo-boa repository and add some links to the expected format would help.

**Comment by saltyskip** [comment]
Thanks for the response, I've bumped up the previous issue regarding python ABI's in the neo-boa repo

**Comment by ixje** [comment]
closing in favour of https://github.com/CityOfZion/neo-boa/issues/34
