### ISSUE TITLE
How I can pass arguments to ScriptBuilder?

### ISSUE THREAD

**Issue by kartava** [CityOfZion/neo-python#927]
Hi! I'm interacting with contract methods as in this [example](https://github.com/CityOfZion/neo-python/blob/master/examples/build_raw_transactions.py#L158).

And I need to call the `transfer` method and pass the following arguments (`from`, `to`, `amount`) to this  method.

Could you please describe how I can do it?

**Comment by ixje** [comment]
Have a look at the `ScriptBuilder` class
e.g. https://github.com/CityOfZion/neo-python/blob/fe90f62e123d720d4281c79af0598d9df9e776fb/neo/VM/ScriptBuilder.py#L179

**Comment by kartava** [comment]
> Have a look at the `ScriptBuilder` class
> e.g.
> 
> [neo-python/neo/VM/ScriptBuilder.py](https://github.com/CityOfZion/neo-python/blob/fe90f62e123d720d4281c79af0598d9df9e776fb/neo/VM/ScriptBuilder.py#L179)
> Line 179 in [fe90f62](/CityOfZion/neo-python/commit/fe90f62e123d720d4281c79af0598d9df9e776fb)
>  def EmitAppCallWithOperationAndArgs(self, script_hash, operation, args):

It would be great if you showed an example with the correct format of the arguments.

**Comment by ixje** [comment]
You can find references / examples in the main project. Just search for them.

**Comment by kartava** [comment]
I hope this will save a lot of time for someone.

```
from neocore.BigInteger import BigInteger

...

smartcontract_scripthash = UInt160.ParseString("31730cc9a1844891a3bafd1aa929a4142860d8d3")
destination_script_hash = address_to_scripthash(destination_address)

sb = ScriptBuilder()

params = [
    source_script_hash.ToBytes(),
    destination_script_hash.ToBytes(),
    BigInteger(amount)
]

sb.EmitAppCallWithOperationAndArgs(smartcontract_scripthash, 'transfer', params)

...
```
