### ISSUE TITLE
Cannot send raw transaction.

### ISSUE THREAD

**Issue by kartava** [CityOfZion/neo-python#931]
I'm trying to use this [example](https://github.com/CityOfZion/neo-python/blob/master/examples/build_raw_transactions.py#L53) with my data.

And the following error appears:
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -504,
    "message": "Block or transaction validation failed."
  }
}
```

`contract_tx.ToJson()  result →`:
```
{
  "type": "ContractTransaction",
  "txid": "0xe49f80c0375968dc51e5ea785a9de0590fc2ede289c4eee79e189050bd8cd327",
  "size": 178,
  "version": 0,
  "attributes": [
    {
      "usage": 144,
      "data": "c87823b9fd4c4dcfa79647b968379517"
    }
  ],
  "vout": [
    {
      "n": 0,
      "asset": "0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b",
      "value": "10",
      "address": "ARRDk72dypPm9KqRJLGhJhFtvyAVTK9Dw5"
    },
    {
      "n": 1,
      "asset": "0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b",
      "value": "99998856",
      "address": "AHMzmNbxynX1HUx5J3vDcYfU1bCwSaYVve"
    }
  ],
  "vin": [
    {
      "txid": "0x9e2690583f52ede67410084edf21972802082bcb44694c97b9e5ab5a89efb2cf",
      "vout": 2
    }
  ],
  "sys_fee": "0",
  "net_fee": "0",
  "scripts": []
}
```

**Comment by ixje** [comment]
At first sight it looks like you have not signed your transaction.

**Comment by kartava** [comment]
Could you please check [example](https://github.com/CityOfZion/neo-python/blob/master/examples/build_raw_transactions.py#L53) on your network.

It seems that the code in example is not actual.

**Comment by jseagrave21** [comment]
@kartava the examples are tested here: https://github.com/CityOfZion/neo-python/blob/master/examples/test_build_raw_transactions.py

On a related note, there is an ongoing project to product a[ lightweight SDK API](https://github.com/CityOfZion/neo-python/issues/883) which includes a [raw transaction builder class](https://github.com/CityOfZion/neo-python/issues/886) which is fully functional here: https://github.com/jseagrave21/neo-python/blob/raw-transaction-class/neo/Core/TX/RawTransaction.py

Please note, if you are using a private net, you will need to be running NeoScan concurrently and use its endpoint for your selection in `Network()`. For example, this transaction https://neoscan-testnet.io/transaction/dc25e671476550fe837897522bac6b03f7dd83d8a29fe81a2b36e84ad92b9f7b was created with the script:
```
from neo.Core.TX.RawTransaction import RawTransaction
import json

tx = RawTransaction()
tx.TXType("Contract")
# note that the default network is testnet so tx.Network() is not needed here
tx.Address("AJ7f4nsBXxTBddgHGyKPjF9n11aK73G3oZ")
tx.AddInputs("neo")
tx.AddOutput("neo", "AMtzvuks9yQnYgqB3scjK53oUWj7i7YZxP", 2)
tx.CalcChange()
tx.Sign("OMITTED", "OMITTED")

txid = tx.GetTXID()
print(txid)
res = tx.ToJson()
print("{}".format(json.dumps(res, indent=4)))
res = tx.GetRawTX()
print(res)
```
Then it was sent via RPC using "sendrawtransaction".

**Comment by kartava** [comment]
Thank you! This example works for me.
