### ISSUE TITLE
Exception when trying to run the TestInvokeContract from python code

### ISSUE THREAD

**Issue by tariqtm** [CityOfZion/neo-python#936]
### Current behavior
I have setup a privatenet with neo-scan as described in the following link 

https://github.com/slipo/neo-scan-docker

Which uses the docker pre-built image of privatenet. When i execute the testinvoke command from np-prompt -p i.e. neo-cli it works fine as displayed below:

![image](https://user-images.githubusercontent.com/22135951/56864937-b531ab00-69e1-11e9-8f4b-1fd1c549f74e.png)

But when i try to use the same via python code (api code used as middleware based on the example provided here https://github.com/CityOfZion/neo-python/blob/master/examples/smart-contract-rest-api.py) the following error is generated

![image](https://user-images.githubusercontent.com/22135951/56865009-7c460600-69e2-11e9-9c47-2e3907c157c5.png)

This is the code that i am using to send the testinvoke call

imported this module
from neo.Prompt.Commands.Invoke import TestInvokeContract, test_invoke

and this is how its used
![image](https://user-images.githubusercontent.com/22135951/56865047-0d1ce180-69e3-11e9-8b1b-22481bff32cc.png)
 the highlighted line throws the exception displayed in the screen above.

### Your environment

Let us know in what environment you're running into the issue:

- OS: Linux  
- neo-python version: 0.8.2
- Python version: 3.6

**Comment by ixje** [comment]
> But when i try to use the same via python code (api code used as middleware based on the example provided here https://github.com/CityOfZion/neo-python/blob/master/examples/smart-contract-rest-api.py) the following error is generated

I'm not completely following what you're doing. The `smart-contract-rest-api.py` you link to is a standalone minimal version to connect to the blockchain and has some Rest API, but nothing that can invoke. I'm guessing you modified one of the endpoints and are calling it.  I can't tell how you modified it, nor how you call it. It seems like the JSON request you're making is wrong or the response you're creating given that there is a JSON error.

**Comment by tariqtm** [comment]
Thanks a lot ixje for the response ..

Yes, i have modified one of the endpoints and then calling it. Here is the modification :

--This is the endpoint code
@app.route('/mycall', methods=['POST'])
@catch_exceptions
@authenticated
@json_response
def create_my_call(request):
    # Parse POST JSON body
    body = json.loads(request.content.read().decode("utf-8"))
    p = Myclass(body["key"],body["value"])
    res = {}
    try:
        res = mycontract.create(p)
    except Exception as e:
        res["error"] = True
        res["message"] = e
    return res

--This is myclass containing both the properties i.e. key and value
class myclass(object):
    def __init__(self, key, value):
        self.key = key
        self.value = value

--This is mycontract class containing the "create" method
def create(self,myclass):
        logger.info("Creating a new record")
        if self.wallet_has_gas():
            logger.info("Wallet has Gas")
            args = [myclass.key, myclass.value]
            return {"tx": self.invoke_contract("register", args)}
        else:
            return {"error": True, "message": "Wallet has no gas, wait for the next block"}

--This is invoke_contract in the same class
def invoke_contract(self, command, args):
        logger.info("Invoking a smart contract")

        if not self.Wallet.IsSynced:
            logger.error("Node is still catching up with blockchain.")
            raise RuntimeError('Node is still catching up with blockchain.')
        argshex = []
        for a in args:
            argshex.append(binascii.hexlify(a.encode('utf-8')))

        params = [self.contract_hash, command, argshex]
        logger.info(params)
        
        try:
            tx, fee, results, num_ops = TestInvokeContract(self.Wallet, params)
        except Exception as e:
            logger.error("Some error in TestInvokeContract : %s (%s)" % (e, tx))

--and finally .. this is how i am calling the endpoint where the exception is occurring:
curl -X POST -H "Authorization: Bearer 123" -d '{ "key": "my_key", "value" : "my_value" }' 152.29.0.3:8081/mycall

Thanks,
Tariq

**Comment by ixje** [comment]
I would look at the result of
> return **{"tx": self.invoke_contract("register", args)}**

I'm guessing that might hold something unexpected and causes this to fail
https://github.com/CityOfZion/neo-python/blob/e002fa580388aedb6b83ef8fd8a4a2867b858813/neo/Network/api/decorators.py#L24

**Comment by tariqtm** [comment]
ixje, 

I have investigated the issue further .. The following line of code

tx, fee, results, num_ops = TestInvokeContract(self.Wallet, params)

is generating the error message "Invalid list operation", which is the main issue. The other json serializable message is caused due to this exception. 

Please help me find the reason for "Invalid list operation" message on TestInvokeContract.

Thanks

**Comment by ixje** [comment]
```python
import traceback

try:
   tx, fee, results, num_ops = TestInvokeContract(self.Wallet, params)
except Exception:
   traceback.print_exc()
```
wrap your code in this and see where the exception comes from

**Comment by tariqtm** [comment]
This is the output of traceback.print_exc

Traceback (most recent call last):
  File "/neo-python/neo/Prompt/Commands/Invoke.py", line 341, in test_invoke
    events.emit(event.event_type, event)
  File "/usr/local/lib/python3.6/dist-packages/pymitter/__init__.py", line 282, in emit
    remove = [l for l in listeners if not l(*args, **kwargs)]
  File "/usr/local/lib/python3.6/dist-packages/pymitter/__init__.py", line 282, in <listcomp>
    remove = [l for l in listeners if not l(*args, **kwargs)]
  File "/usr/local/lib/python3.6/dist-packages/pymitter/__init__.py", line 310, in __call__
    self.func(*args, **kwargs)
  File "/neo-python/neo/contrib/smartcontract.py", line 72, in call_on_event
    [event_handler(sc_event) for event_handler in handlers]
  File "/neo-python/neo/contrib/smartcontract.py", line 72, in <listcomp>
    [event_handler(sc_event) for event_handler in handlers]
  File "smart-contract-rest-api.py", line 113, in sc_notify
    if not len(event.event_payload):
TypeError: object of type 'ContractParameter' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/neo-python/mycontract.py", line 64, in invoke_contract
    tx, fee, results, num_ops = TestInvokeContract(self.Wallet, params)
  File "/neo-python/neo/Prompt/Commands/Invoke.py", line 222, in TestInvokeContract
    return test_invoke(out, wallet, outputs, withdrawal_tx, from_addr, min_fee, invoke_attrs=invoke_attrs, owners=owners)
  File "/neo-python/neo/Prompt/Commands/Invoke.py", line 380, in test_invoke
    service.ExecutionCompleted(engine, False, e)
  File "/neo-python/neo/SmartContract/StateMachine.py", line 86, in ExecutionCompleted
    super(StateMachine, self).ExecutionCompleted(engine, success, error)
  File "/neo-python/neo/SmartContract/StateReader.py", line 307, in ExecutionCompleted
    [payload.Value.append(ContractParameter.ToParameter(item)) for item in engine.CurrentContext.EvaluationStack.Items]
  File "/neo-python/neo/VM/ExecutionEngine.py", line 79, in CurrentContext
    return self._InvocationStack.Peek()
  File "/neo-python/neo/VM/RandomAccessStack.py", line 55, in Peek
    raise Exception("Invalid list operation")
Exception: Invalid list operation

**Comment by ixje** [comment]
change this
https://github.com/CityOfZion/neo-python/blob/e002fa580388aedb6b83ef8fd8a4a2867b858813/neo/SmartContract/StateReader.py#L305-L307

to 
```python
            if engine._InvocationStack.Count > 1:
                [payload.Value.append(ContractParameter.ToParameter(item)) for item in engine.CurrentContext.EvaluationStack.Items]
```

As you can tell from the comment in the code linked you probably have a mistake in your smart contract. However, you should not be getting the exception shown, so please resolve that with the above code.

**Comment by tariqtm** [comment]
Thanks a lot ixje, changing the line of code as you suggested solved the problem. That error has gone away and now TestInvokeContract is executing without errors. So, this issue can be closed now.

But now, i am getting a "NoneType: None" when executing the TestInvokeContract. all four return params i.e. tx, fee, results, num_ops are returned as None.

Even though the SmartContract Runtime.Notify event shows as success and also a transaction hash is displayed as shown below:. 
 
[I 190430 12:54:02 smart-contract-rest-api:110] SmartContract Runtime.Notify event: SmartContractEvent(event_type=SmartContract.Runtime.Notify, event_payload=<neo.SmartContract.ContractParameter.ContractParameter object at 0x7fe7a84241d0>, contract_hash=63edfa9f75995be0aa6298b217b2c869a45a1ce2, block_number=7708, tx_hash=8461b9eb591c417286fff59709995537392a2938c6ebd84a0ef6bd5dad4bead8, execution_success=True, test_mode=True)
NoneType: None

Can you please guide me what could be the issue? Is it still due to some mistake in smartcontract?

I will be really thankful for the help.

Regards,
Tariq

**Comment by ixje** [comment]
Sorry I can't tell from the error message. You'll have to put some breakpoints and debug the script to see why choose a branch that results in `None`. I would have to do the same. Glad the original issue was resolved
