### ISSUE TITLE
InteropService Clone() - list index out of range

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo-python#94]
Observed while syncing test net

> [I 171120 13:40:57 EventHub:99] [SmartContract.Execution.Success][646058] [8947279d24cfcac050e14c84d748ec78aeea6dd4] [tx a0f11cf23d1c828d782beae8103b6089e036aacce776a55ccfb544994f1925ea] [b'\x00']
[E 171120 13:40:57 ExecutionEngine:800] COULD NOT EXECUTE OP: list assignment index out of range b'\xc4' SETITEM
[E 171120 13:40:57 ExecutionEngine:801] list assignment index out of range
    Traceback (most recent call last):
      File "/Users/erik/Documents/code/neo-python/neo/VM/ExecutionEngine.py", line 798, in StepInto
        self.ExecuteOp(op, self.CurrentContext)
      File "/Users/erik/Documents/code/neo-python/neo/VM/ExecutionEngine.py", line 710, in ExecuteOp
        newItem = newItem.Clone()
      File "/Users/erik/Documents/code/neo-python/neo/VM/InteropService.py", line 265, in Clone
        newArray[i] = None
    IndexError: list assignment index out of range
[I 171120 13:40:57 EventHub:99] [SmartContract.Execution.Fail][646061] [8947279d24cfcac050e14c84d748ec78aeea6dd4] [tx 18378c04113089f56ce36ac474a2a6da9da249db628e37ba4c23bec370834a5c] [[[<neo.Core.TX.InvocationTransaction.InvocationTransaction object at 0x107011978>, <neo.Core.TX.Transaction.TransactionOutput object at 0x10590f630>, b'/<\xaa!\xd8(\x94\x02\xf2\x96\tT\x9a2\xed\xa0aZ7\xb7', [<neo.Core.TX.Transaction.TransactionOutput object at 0x117dfa550>, <neo.Core.TX.Transaction.TransactionOutput object at 0x117dfaeb8>, <neo.Core.TX.Transaction.TransactionOutput object at 0x120613160>], b"\xd4m\xea\xaex\xecH\xd7\x84L\xe1P\xc0\xca\xcf$\x9d'G\x89", 10000000000, [<neo.Core.TX.Transaction.TransactionOutput object at 0x117dfa550>, <neo.Core.TX.Transaction.TransactionOutput object at 0x117dfaeb8>, <neo.Core.TX.Transaction.TransactionOutput object at 0x120613160>], 3, <neo.Core.TX.Transaction.TransactionOutput object at 0x120613160>, False, None, None], 10], None, 6]

**Comment by localhuman** [comment]
should be fixed now in 7172b342c0349d9fd07673182dd9fd591af8f46a
