### ISSUE TITLE
various PR + review

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo-python#946]
Creating an issue to collect information for rewards

@jseagrave21 contributed the following PR's directly into #934 via my personal repo
https://github.com/ixje/neo-python/pull/13
https://github.com/ixje/neo-python/pull/14
https://github.com/ixje/neo-python/pull/16

and has continued testing the branch. 

350 points

**Comment by lllwvlvwlll** [comment]
https://neoscan.io/transaction/c382c87ce7282664dc849fef5cb8c8de22cf3b596dd1b4e85c87efb194bb2003
