### ISSUE TITLE
ExecutionEngine.py - exception BigInteger no attribute Sign

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo-python#95]
While observing testnet syncing. Probably could use a more graceful handling.

> [I 171120 13:43:59 EventHub:99] [SmartContract.Execution.Success][718081] [17f7abfbd4ab65a9aef430e30e05c109c373b3fe] [tx d8968bd24b817e28a080a3c94e757a3309497ae95a2017b30fd9ea130ee59a84] [<neo.Core.State.ContractState.ContractState object at 0x12255d748>]
> [E 171120 13:43:59 ExecutionEngine:800] COULD NOT EXECUTE OP: 'BigInteger' object has no attribute 'Sign' b'\x8d' SIGN
> [E 171120 13:43:59 ExecutionEngine:801] 'BigInteger' object has no attribute 'Sign'
>     Traceback (most recent call last):
>       File "/Users/erik/Documents/code/neo-python/neo/VM/ExecutionEngine.py", line 798, in StepInto
>         self.ExecuteOp(op, self.CurrentContext)
>       File "/Users/erik/Documents/code/neo-python/neo/VM/ExecutionEngine.py", line 414, in ExecuteOp
>         estack.PushT(x.Sign)
>     AttributeError: 'BigInteger' object has no attribute 'Sign'

**Comment by localhuman** [comment]
Looks like we need to implement the `Sign` method on `BigInteger` to return whether it is a positive or negative

**Comment by metachris** [comment]
Great that these kind of things are now coming to light with the new
logging! :+1:

**Comment by localhuman** [comment]
Should be fixed now in 7172b342c0349d9fd07673182dd9fd591af8f46a
