### ISSUE TITLE
np-bootstrap hangs at confirm prompt

### ISSUE THREAD

**Issue by brianlenz** [CityOfZion/neo-python#984]
### Current behavior
- Are you using the latest available version?
  * Yes (`development` branch)
- What is the problem?
  * `np-bootstrap` hangs at the `confirm` prompt when attempting to overwrite the MainNet chain:
```
(venv) $ np-bootstrap -m
This will overwrite any data currently in ~/.neopython/Chains/Main.
Type 'confirm' to continue
[confirm]>
```

### Expected behavior

- What should be happening?
You should be able to type `confirm` and continue the process.

### How to reproduce

- Please explain the steps to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of this project.
Just run `np-bootstrap -m`. Once the `confirm` prompt appears, the process hangs and accepts no more input until it is killed.

If you run `np-bootstrap -m -s`, it works fine since it skips the prompt, so it has something to do with the `confirm` prompt behavior.

### Your environment

Let us know in what environment you're running into the issue:

- OS: macOS 10.14.5
- neo-python version: `development` branch (v0.8.5-dev)
- Python version: 3.7.4

**Comment by ixje** [comment]
Thanks Brian, I know what the issue is and will resolve it before release. By keeping this issue open it will hopefully lead users here so I can give them the following warning

**Warning**
The latest available bootstrap files should not be used with the development branch. The database is not compatible.

**Comment by skinderis** [comment]
do np-bootstrap -ms, -s is to skip confirm
